import React from 'react';
import { Route, Routes, Link, BrowserRouter } from 'react-router-dom';
import HomePage from './HomePage';
import AnimalCatalogue from './AnimalCatalogue';
import RandomFact from './RandomFact';
import Animal from './Animal';
import giantPandaImage from "./Images/giantpanda.png"
import amurLeopardImage from "./Images/amur-leopard.png"
import orangutanImage from "./Images/orangutan.png"
import saolaImage from "./Images/saola.png"
import snowLeopardImage from "./Images/leopard.png"
import kakapoImage from "./Images/kakapoa.png"
import javanRhinoImage from "./Images/javanrhino.png"
import blackRhinoImage from "./Images/blackrhino.png"
import vaquitaImage from "./Images/vaquita.png"
import seaTurtleImage from "./Images/seaturtle.png"
import siberianTigerImage from "./Images/siberian-tiger.png"
import blueWhaleImage from "./Images/bluewhale.png"
import cheetahImage from "./Images/cheetah.png"
import elephantImage from "./Images/indian-elephant.png"
import polarBearImage from "./Images/polarbear.png"
import redPandaImage from "./Images/red-panda.png"
import sumatranTigerImage from "./Images/sumatran-tiger.png"
import greenSeaTurtleImage from "./Images/green-sea-turtle.png"
import pygmyHippoImage from "./Images/pygmy-hippo.png"
import wildDogImage from "./Images/african-wild-dog.png"
import iberianLynxImage from "./Images/iberian-lynx.png"
import mountainGorillaImage from "./Images/mountain-gorilla.png"
import galapagosTortoiseImage from "./Images/galapagos-turtle.png"
import tapanuliOrangutanImage from "./Images/tapanuli-orangutan.png"
import hawksbillTurtleImage from "./Images/hawksbill-turtle.png"
import addaxImage from "./Images/addax.png"
import pygmyThreeToedSlothImage from "./Images/Pygmy-Three-Toed-Sloth.png"
import bactrianCamelImage from "./Images/Wild-Bactrian-Camel.png"
import siameseCrocodileImage from "./Images/siamese-croc.png"
import saigaImage from "./Images/Saiga-Antelope.png"
import scarletMacawImage from "./Images/Scarlet-Macaw.png"
import tigerQuollImage from "./Images/Tiger-Quoll.png"
import japaneseCraneImage from "./Images/Japanese-Crane.png"
import dugongImage from "./Images/Dugong.png"
import bonoboImage from "./Images/Bonobo.png"
import andeanCondorImage from "./Images/Andean-Condor.png"
import blackFootedFerretImage from "./Images/Black-Footed-Ferret.png"
import leatherbackSeaTurtleImage from "./Images/Leatherback-Sea-Turtle.png"
import komodoDragonImage from "./Images/Komodo-Dragon.png"
import sundaTigerImage from "./Images/Sunda-Tiger.png"
import cloudedLeopardImage from "./Images/Sunda-Clouded-Leopard.png"
import gorillaImage from "./Images/Western-Lowland-Gorilla.png"
import indusRiverDolphinImage from "./Images/Indus-River-Dolphin.png"
import redCrownedCraneImage from "./Images/Red-Crowned-Crane.png"
import okapiImage from "./Images/okapi.png"
import asiaticLionImage from "./Images/Asiatic-Lion.png"
import yellowEyedPenguinImage from "./Images/Yellow-Eyed-Penguin.png"
import marmosetImage from "./Images/Pygmy-Marmoset.png"
import pyreneanIbexImage from "./Images/Pyrenean-Ibex.png"
import bermudaPetrelImage from "./Images/Bermuda-Petrel.png"
import northernWhiteRhinoImage from "./Images/Northern-White-Rhino.png"
import baijiImage from "./Images/Baiji.png"
import hirolaImage from "./Images/Hirola.png"
import amadoniWolfImage from "./Images/Amadoni-Wolf.png"
import giantArmadilloImage from "./Images/Giant-Armadillo.png"
import iliPikaImage from "./Images/Ili-Pika.png"
import ethiopianWolfImage from "./Images/Ethiopian-Wolf.png"
import javanSlowLorisImage from "./Images/Javan-Slow-Loris.png"
import westernSwampTortoiseImage from "./Images/Western-Swamp-Tortoise.png"
import madagascarFishEagleImage from "./Images/Madagascar-Fish-Eagle.png"
import gangesDolphinImage from "./Images/Ganges-River-Dolphin.png"
import iberianWolfImage from "./Images/Iberian-Wolf.png"
import greaterBambooLemurImage from "./Images/Greater-Bamboo-Lemur.png"
import giantButterflyImage from "./Images/Queen-Alexandra's-Birdwing.png"
import blueThroatedMacawImage from "./Images/Blue-Throated-Macaw.png"
import balkanLynxImage from "./Images/Balkan-Lynx.png"
import oryxImage from "./Images/Scimitar-Horned-Oryx.png"
import darwinFrogImage from "./Images/Darwin's-Frog.png"
import yellowFootedWallabyImage from "./Images/Yellow-Footed-Rock-Wallaby.png"
import galapagosPenguinImage from "./Images/Galapagos-Penguin.png"
import addraGazelleImage from "./Images/Addra-Gazelle.png"
import prairieChickenImage from "./Images/Attwater's-Prairie-Chicken.png"
import monkSealImage from "./Images/Hawaiian-Monk-Seal.png"
import floridaPantherImage from "./Images/Florida-Panther.png"
import spixMacawImage from "./Images/Spix's-Macaw.png"
import antipodesParakeetImage from "./Images/Antipodes-Island-Parakeet.png"
import palawanPeacockPheasantImage from "./Images/Palawan-Peacock-Pheasant.png"
import mexicanGrayWolfImage from "./Images/Mexican-Gray-Wolf.png"
import angelSharkImage from "./Images/Angel-Shark.png"
import chineseGiantSalamanderImage from "./Images/Chinese-Giant-Salamander.png"
import ethiopianHighlandWolfImage from "./Images/Ethiopian-Highland-Wolf.png"
import laysanAlbatrossImage from "./Images/Laysan-Albatross.png"
import blackFacedSpoonbillImage from "./Images/Black-Faced-Spoonbill.png"
import mountainNyalaImage from "./Images/Mountain-Nyala.png"
import markhorImage from "./Images/Markhor.png"
import giantIbisImage from "./Images/Giant-Ibis.png"
import yangtzeSoftshellTurtleImage from "./Images/Yangtze-Softshell-Turtle.png"
import takaheImage from "./Images/Takahe.png"
import philippineTarsierImage from "./Images/Philippine-Tarsier.png"
const animalDesc = {
    giantPanda: "The Giant Panda (Ailuropoda melanoleuca) is a beloved and iconic symbol of wildlife conservation, known for its distinctive black and white fur and gentle demeanor; native to the mountainous regions of central China, they live in bamboo forests, feeding almost exclusively on bamboo; skilled climbers and swimmers, pandas face critical threats such as habitat loss due to deforestation, agricultural expansion, and human encroachment, as well as low reproductive rates; conservation efforts, including habitat restoration, captive breeding, and legal protections, have helped stabilize their population, but ongoing efforts are crucial for their survival in the wild.",
    amurLeopard: "The Amur Leopard is a critically endangered leopard subspecies native to the temperate forests of the Russian Far East and northeastern China. It has a pale, golden coat with rosettes and is adapted to cold climates. Its diet includes roe deer, sika deer, and hares. Major threats include habitat loss, poaching, and human-wildlife conflict. Conservation actions involve habitat protection, anti-poaching measures, and cross-border cooperation. The population is estimated to be fewer than 100 individuals.",
    snowLeopard: "The Snow Leopard (Panthera uncia) inhabits the mountain ranges of Central and South Asia, known for its thick fur and long tail. It preys on large herbivores like blue sheep and ibex. Snow leopards face threats from poaching, habitat loss, and retaliatory killings. Conservation efforts focus on habitat protection, anti-poaching measures, and community engagement. The population is estimated to be between 4,000 and 6,500 individuals.",
    blackRhino: "The Black Rhino (Diceros bicornis) is a critically endangered species found in various regions of Africa, including Kenya and South Africa. They are distinguished by their hooked-shaped upper lips and primarily graze on shrubs and trees. Major threats include poaching for their horns and habitat loss due to agricultural expansion. Conservation efforts involve anti-poaching patrols, habitat restoration, and legal protection. The population is currently around 5,000 individuals.",
    orangutan: "The Orangutan (Pongo spp.) is native to the rainforests of Borneo and Sumatra. These great apes are critically endangered due to deforestation, illegal pet trade, and habitat destruction. Orangutans primarily feed on fruits, leaves, and insects. Conservation actions include habitat protection, rehabilitation, and reforestation programs. The wild population of Sumatran orangutans is estimated to be fewer than 14,000 individuals.",
    seaTurtle: "Various species of sea turtles are critically endangered due to pollution, habitat loss, and poaching. Sea turtles can be found in tropical and subtropical oceans, and they feed on a range of diets including jellyfish, crustaceans, and sea grasses. Conservation efforts focus on protecting nesting sites, reducing bycatch, and combating illegal trade. The population varies significantly by species, with some having fewer than 1,000 individuals remaining.",
    vaquita: "The Vaquita (Phocoena sinus) is a critically endangered species of porpoise found in the northern part of the Gulf of California. Known for its small size and distinctive dark rings around its eyes, the vaquita faces imminent extinction due to entanglement in illegal gillnets used for fishing totoaba fish. Conservation measures include banning gillnets, increased patrolling, and advocacy for alternative fishing methods. Fewer than 10 individuals are estimated to remain.",
    saola: "The Saola (Pseudoryx nghetinhensis) is a critically endangered bovid native to the Annamite Range of Vietnam and Laos. It was first discovered in 1992 and is known for its long, straight horns and elusive nature. Major threats include habitat loss and hunting. Conservation actions include habitat protection and anti-poaching measures. The population is believed to be fewer than 100 individuals.",
    javanRhino: "The Javan Rhino (Rhinoceros sondaicus) is one of the world's rarest large mammals, found only in Ujung Kulon National Park in Indonesia. It has a single horn and primarily feeds on leaves, shoots, and fruits. Threats include habitat loss and natural disasters. Conservation efforts involve habitat protection and monitoring. The population is estimated to be around 70 individuals.",
    kākāpō: "The Kākāpō (Strigops habroptilus) is a critically endangered flightless parrot native to New Zealand. It is known for its nocturnal behavior and large size. The kākāpō faces threats from habitat destruction and predation by introduced species. Conservation actions include habitat restoration, predator control, and breeding programs. The population is currently around 200 individuals.",
    siberianTiger: "The Siberian Tiger (Panthera tigris altaica) is the largest tiger subspecies, native to the forests of eastern Russia. It primarily hunts deer and wild boar. Major threats to its survival include poaching for its fur and body parts, as well as habitat loss due to logging and human encroachment. Conservation efforts include anti-poaching laws, habitat protection, and breeding programs. The current population is estimated to be around 500 individuals.",
    blueWhale: "The Blue Whale (Balaenoptera musculus) is the largest animal to have ever lived on Earth, found in oceans worldwide. It feeds almost exclusively on krill and plays a crucial role in marine ecosystems. Threats include ship strikes and ocean noise pollution. Conservation efforts focus on marine protection zones and international cooperation to reduce ship collisions. The population is estimated to be around 2,000 individuals.",
    cheetah: "The Cheetah (Acinonyx jubatus) is the fastest land animal, capable of reaching speeds up to 60 miles per hour in short bursts. Found in African savannas, it primarily hunts gazelles and other small to medium-sized ungulates. Habitat fragmentation and poaching pose major threats to their survival. Conservation efforts include habitat restoration, anti-poaching initiatives, and community engagement. Approximately 7,100 individuals remain in the wild.",
    indianElephant: "The Indian Elephant (Elephas maximus indicus) is a subspecies of the Asian elephant, native to India and Southeast Asia. It plays a vital role in maintaining the forest ecosystems by spreading seeds. However, poaching for ivory, habitat loss, and human-elephant conflict are significant threats. Conservation corridors and anti-poaching laws are crucial in ensuring their survival. The population is estimated to be around 20,000 individuals.",
    polarBear: "The Polar Bear (Ursus maritimus) is a carnivorous bear native to the Arctic, relying on sea ice to hunt seals. Climate change, which is rapidly melting Arctic ice, is the primary threat to its survival. Conservation efforts focus on reducing greenhouse gas emissions, protecting Arctic habitats, and mitigating human-bear conflicts. The current population is approximately 25,000 individuals.",
    redPanda: "The Red Panda (Ailurus fulgens) is a small mammal native to the Himalayas, known for its reddish-brown fur and playful behavior. It primarily eats bamboo but also consumes fruits, insects, and small mammals. Habitat destruction due to deforestation and poaching for their pelts are the main threats. Conservation actions include habitat restoration and the establishment of protected areas. The population is estimated to be around 10,000 individuals.",
    sumatranTiger: "The Sumatran Tiger (Panthera tigris sumatrae) is the smallest surviving tiger subspecies, found only on the Indonesian island of Sumatra. It preys on deer, wild boar, and other large mammals. Poaching and habitat destruction are the primary threats to its survival. Conservation measures include anti-poaching patrols, habitat protection, and breeding programs. Fewer than 400 individuals remain in the wild.",
    greenSeaTurtle: "The Green Sea Turtle (Chelonia mydas) is a large sea turtle species that inhabits tropical and subtropical oceans around the world. It feeds primarily on seagrass and plays a critical role in maintaining healthy marine ecosystems. Threats include pollution, bycatch in fishing gear, and habitat loss. Conservation efforts focus on protecting nesting sites, reducing bycatch, and combating illegal trade. The population is estimated to be around 8,500 individuals.",
    pygmyHippo: "The Pygmy Hippopotamus (Choeropsis liberiensis) is a small, nocturnal species of hippo native to the swamps and forests of West Africa. Unlike its larger relative, the common hippo, it is reclusive and solitary. Major threats include deforestation and poaching. Conservation actions involve protecting their habitats, enforcing anti-poaching laws, and raising awareness. The population is estimated to be around 3,000 individuals.",
    africanWildDog: "The African Wild Dog (Lycaon pictus) is a highly social predator native to sub-Saharan Africa. It lives in packs and hunts antelope, wildebeest, and other large prey. Habitat fragmentation and human-wildlife conflict are significant threats to their survival. Conservation efforts include anti-poaching initiatives, habitat protection, and community-based conservation programs. The population is estimated to be around 6,600 individuals.",
    iberianLynx: "The Iberian Lynx (Lynx pardinus) is one of the world's most endangered cats, found in parts of Spain and Portugal. It primarily feeds on rabbits, and its survival is closely linked to rabbit populations. Habitat loss and hunting have significantly reduced its range. Conservation efforts focus on prey reintroduction, habitat protection, and breeding programs. The current population is estimated to be around 400 individuals.",
    mountainGorilla: "The Mountain Gorilla (Gorilla beringei beringei) inhabits the montane forests of Central Africa. It feeds on a variety of vegetation, including leaves, stems, and fruit. Poaching and habitat loss due to human activities pose major threats to its survival. Conservation efforts include anti-poaching patrols and habitat protection in national parks. The population is estimated to be around 1,000 individuals.",
    galapagosTortoise: "The Galapagos Tortoise (Chelonoidis spp.) is native to the Galapagos Islands and is the largest tortoise species. It feeds on grasses, cacti, and other vegetation. Invasive species such as rats and pigs threaten their survival, along with habitat destruction. Conservation actions include invasive species control and habitat protection. The population is around 15,000 individuals.",
    tapanuliOrangutan: "The Tapanuli Orangutan (Pongo tapanuliensis) is a critically endangered species found in the rainforests of Sumatra. It primarily eats fruits, leaves, and small insects. Deforestation and poaching are significant threats to their population. Conservation efforts focus on habitat protection, anti-poaching patrols, and the promotion of sustainable palm oil. Fewer than 800 individuals remain in the wild.",
    hawksbillTurtle: "The Hawksbill Turtle (Eretmochelys imbricata) inhabits tropical coral reefs and feeds on sponges and jellyfish. Habitat destruction, illegal trade, and climate change are major threats to their survival. Conservation actions include marine protected areas and global efforts to reduce illegal trade. The population is currently estimated to be around 25,000 individuals.",
    addax: "The Addax (Addax nasomaculatus) is a critically endangered antelope species that inhabits the Sahara Desert. It feeds on grasses and shrubs. Poaching and habitat loss are the primary threats to its survival. Conservation efforts include habitat protection and breeding programs. Fewer than 100 individuals remain in the wild.                                                     ",
    pygmyThreeToedSloth: "The Pygmy Three-toed Sloth (Bradypus pygmaeus) is a small sloth species found only in the mangroves of Panama's Isla Escudo de Veraguas. It primarily feeds on mangrove leaves. Habitat loss due to human activities is the main threat to its survival. Conservation efforts focus on eco-tourism management and habitat protection. Fewer than 100 individuals remain.",
    bactrianCamel: "The Wild Bactrian Camel (Camelus ferus) is critically endangered and is native to the deserts of Central Asia. It primarily feeds on grasses and shrubs. Habitat loss due to mining and human encroachment, along with poaching, are major threats. Conservation efforts include habitat protection and establishing protected areas. The population is estimated to be around 1,000 individuals.",
    siameseCrocodile: "The Siamese Crocodile (Crocodylus siamensis) is critically endangered and found in freshwater rivers and lakes in Southeast Asia. It feeds on fish, amphibians, and small mammals. Habitat loss, pollution, and poaching are the main threats to its survival. Conservation efforts focus on habitat protection and establishing protected areas. The population is estimated to be around 250 individuals.",
    saigaAntelope: "The Saiga Antelope (Saiga tatarica) is a critically endangered species that roams the steppes of Central Asia. It primarily feeds on grasses and herbs. Poaching and habitat loss are significant threats to their survival. Conservation efforts focus on anti-poaching patrols, habitat restoration, and breeding programs. The population is estimated to be around 5,000 individuals.",
    scarletMacaw: "The Scarlet Macaw (Ara macao) is a brightly colored parrot species found in the rainforests of Central and South America. It feeds on fruits and nuts, playing a key role in seed dispersal. Major threats include habitat loss due to deforestation and the illegal pet trade. Conservation efforts focus on habitat restoration and the prevention of illegal wildlife trade. The population is estimated to be around 20,000 individuals.",
    tigerQuoll: "The Tiger Quoll (Dasyurus maculatus) is the largest carnivorous marsupial in mainland Australia. It primarily feeds on small mammals, birds, and reptiles. Invasive species such as foxes and cats, as well as habitat destruction, threaten its survival. Conservation actions include predator control and habitat protection. The current population is estimated to be around 500 individuals.                                                     ",
    japaneseCrane: "The Japanese Crane (Grus japonensis) is a symbol of longevity and good fortune in Japan. It inhabits wetlands and feeds on fish, amphibians, and plants. Habitat loss due to agricultural expansion is the primary threat. Conservation efforts include wetland restoration and the creation of protected areas. The population is estimated to be around 3,000 individuals.                                                     ",
    dugong: "The Dugong (Dugong dugon) is a marine mammal found in the coastal waters of the Indian and Pacific Oceans. It feeds primarily on seagrass and is closely related to the manatee. Major threats include habitat loss due to coastal development and pollution. Conservation efforts focus on the establishment of marine protection zones and seagrass conservation. The population is estimated to be around 85,000 individuals.",
    bonobo: "The Bonobo (Pan paniscus) is a close relative of the chimpanzee, native to the Congo Basin. It feeds on fruits, leaves, and small animals. Poaching and habitat destruction are significant threats to its survival. Conservation efforts focus on the protection of forested areas and anti-poaching patrols. The population is estimated to be around 5,000 individuals.                                                     ",
    andeanCondor: "The Andean Condor (Vultur gryphus) is one of the largest flying birds, native to the mountain ranges of South America. It feeds on carrion and plays a crucial role in the ecosystem. Threats include poisoning from carcasses and habitat loss. Conservation efforts include the creation of protected areas and public awareness campaigns. The population is estimated to be around 6,700 individuals.",
    blackFootedFerret: "The Black-footed Ferret (Mustela nigripes) is a carnivorous mammal native to North America, primarily preying on prairie dogs. Habitat loss due to agricultural expansion and disease are the primary threats to its survival. Conservation actions include habitat restoration and disease management. The population is estimated to be around 500 individuals.                                                     ",
    leatherbackSeaTurtle: "The Leatherback Sea Turtle (Dermochelys coriacea) is the largest species of sea turtle, inhabiting oceans worldwide. It primarily feeds on jellyfish and is essential for controlling jellyfish populations. Pollution, particularly plastic waste, and habitat destruction are the main threats to its survival. Conservation efforts focus on protecting nesting sites and reducing plastic waste. The population is estimated to be around 34,000 individuals.",
    komodoDragon: "The Komodo Dragon (Varanus komodoensis) is the largest living species of lizard, found on the Indonesian islands of Komodo, Rinca, Flores, and Gili Motang. It preys on deer, pigs, and other large mammals. Habitat loss and human encroachment are the major threats. Conservation efforts include habitat protection and captive breeding programs. The population is estimated to be around 5,000 individuals.",
    sundaTiger: "The Sunda Tiger (Panthera tigris sondaica) is a critically endangered tiger subspecies found only on the island of Sumatra. It preys on deer and wild boar. Poaching and habitat loss due to deforestation are the main threats. Conservation efforts focus on habitat protection and anti-poaching patrols. Fewer than 400 individuals remain in the wild.",
    cloudedLeopard: "The Sunda Clouded Leopard (Neofelis diardi) is native to the islands of Borneo and Sumatra. It primarily feeds on birds, small mammals, and occasionally deer. Deforestation is the primary threat to its survival. Conservation actions include forest protection and efforts to reduce illegal logging. The population is estimated to be around 10,000 individuals.",
    westernLowlandGorilla: "The Western Lowland Gorilla (Gorilla gorilla gorilla) is found in the dense forests of Central Africa. It feeds on fruits, leaves, and small insects. Poaching and habitat destruction are major threats to its survival. Conservation actions include protected areas and anti-poaching patrols. The population is estimated to be around 100,000 individuals.",
    indusRiverDolphin: "The Indus River Dolphin (Platanista gangetica minor) is a freshwater dolphin species found in the Indus River in Pakistan. It primarily feeds on fish and invertebrates. Pollution, water diversion, and habitat loss are major threats. Conservation efforts focus on river protection and pollution control. The population is estimated to be around 1,800 individuals.",
    redCrownedCrane: "The Red-Crowned Crane (Grus japonensis) is a symbol of good fortune in East Asia and is found in wetlands across Japan, China, and Korea. It feeds on insects, fish, and aquatic plants. Habitat loss due to agricultural expansion is the primary threat. Conservation efforts focus on wetland restoration and protection. The population is estimated to be around 3,000 individuals.",
    okapi: "The Okapi (Okapia johnstoni) is a forest-dwelling mammal native to the rainforests of the Congo. It primarily feeds on leaves, fruits, and fungi. Poaching and habitat destruction are the main threats. Conservation efforts focus on anti-poaching patrols and the establishment of protected areas. The population is estimated to be around 3,500 individuals.                                                     ",
    asiaticLion: "The Asiatic Lion (Panthera leo persica) is a critically endangered subspecies found only in the Gir Forest of India. It primarily feeds on deer, antelope, and small mammals. Habitat loss and poaching are the main threats. Conservation actions include protected areas and community engagement to prevent poaching. The population is estimated to be around 600 individuals.                                                     ",
    yellowEyedPenguin: "The Yellow-Eyed Penguin (Megadyptes antipodes) is a rare penguin species found on the coasts of New Zealand. It primarily feeds on fish and squid. Introduced predators, habitat destruction, and human disturbance are significant threats. Conservation actions include habitat restoration and predator control. The population is estimated to be around 4,000 individuals.                                                     ",
    pygmyMarmoset: "The Pygmy Marmoset (Cebuella pygmaea) is the smallest primate species and is native to the rainforests of South America. It feeds on tree sap, insects, and fruits. Habitat loss due to deforestation is the primary threat. Conservation efforts focus on habitat protection and the prevention of illegal pet trade. The population is estimated to be around 50,000 individuals.",
    pyreneanIbex: "The Pyrenean Ibex (Capra pyrenaica pyrenaica) was a wild goat species that inhabited the Pyrenees mountains between France and Spain. Overhunting and habitat loss led to its extinction in the wild. Cloning efforts have been attempted to bring the species back, though the population remains extinct. Conservationists continue to explore biodiversity research.",
    bermudaPetrel: "The Bermuda Petrel (Pterodroma cahow) is a critically endangered seabird native to the coastal regions of Bermuda. It primarily feeds on fish and squid. Habitat destruction and storms are the main threats to its survival. Conservation efforts focus on breeding programs and habitat restoration. The population is estimated to be around 300 individuals.",
    northernWhiteRhino: "The Northern White Rhino (Ceratotherium simum cottoni) is critically endangered, with only two individuals remaining, both in captivity. It once roamed the grasslands of Central Africa, feeding on grasses and leaves. Poaching for its horn led to its near extinction. Conservation efforts focus on breeding programs and IVF techniques to attempt recovery of the species.",
    baiji: "The Baiji (Lipotes vexillifer), or Yangtze River Dolphin, was native to the Yangtze River in China. It fed on fish but faced severe threats from dam construction, pollution, and ship traffic. Despite extensive conservation efforts, the species is considered functionally extinct, with no confirmed sightings in recent years.                                                      ",
    hirola: "The Hirola (Beatragus hunteri), also known as Hunter's antelope, is critically endangered and found in the African savannas. It primarily feeds on grasses. Poaching and habitat loss are the major threats. Conservation actions include anti-poaching patrols and habitat protection. The population is estimated to be around 500 individuals.",
    amadoniWolf: "The Amadoni Wolf is a critically endangered species native to the Brazilian savannas. It preys on small mammals and birds. Habitat loss due to agriculture and hunting are the major threats. Conservation actions focus on habitat protection and raising awareness among local communities. The population is estimated to be around 2,500 individuals.",
    giantArmadillo: "The Giant Armadillo (Priodontes maximus) is native to the tropical forests of South America. It feeds on insects and small animals, playing a key role in soil health. Deforestation and hunting are the main threats. Conservation efforts focus on protected areas and habitat restoration. The population is estimated to be around 1,000 individuals.",
    iliPika: "The Ili Pika (Ochotona iliensis) is a small, rabbit-like mammal found in the mountains of China. It feeds on grasses and herbs. Climate change and habitat loss are significant threats to its survival. Conservation efforts include habitat protection and monitoring populations. The population is estimated to be around 1,000 individuals.",
    ethiopianWolf: "The Ethiopian Wolf (Canis simensis) is the rarest canid species, found in the highlands of Ethiopia. It primarily feeds on rodents. Habitat loss and disease, particularly rabies, are major threats. Conservation efforts focus on vaccination campaigns and habitat protection. The population is estimated to be around 500 individuals.",
    javanSlowLoris: "The Javan Slow Loris (Nycticebus javanicus) is a nocturnal primate found in the tropical forests of Java. It feeds on insects and fruits. The illegal pet trade and habitat loss are the main threats. Conservation actions include anti-poaching measures and habitat restoration. The population size is unknown due to the secretive nature of the species.",
    westernSwampTortoise: "The Western Swamp Tortoise (Pseudemydura umbrina) is critically endangered and found in the wetlands of Australia. It feeds on aquatic plants and insects. Habitat loss due to climate change and urbanization are the main threats. Conservation efforts include captive breeding programs and habitat restoration. The population is estimated to be around 50 individuals.",
    madagascarFishEagle: "The Madagascar Fish Eagle (Haliaeetus vociferoides) is a critically endangered bird found in the coastal wetlands of Madagascar. It primarily feeds on fish. Habitat loss and human disturbance are the major threats to its survival. Conservation efforts include the establishment of protected areas and awareness programs. The population is estimated to be around 120 individuals.",
    gangesDolphin: "The Ganges River Dolphin (Platanista gangetica) is a freshwater dolphin species native to the Ganges River in India. It primarily feeds on fish and crustaceans. Pollution and accidental entanglement in fishing nets are major threats. Conservation efforts include river protection programs and reducing water pollution. The population is estimated to be around 3,700 individuals.",
    iberianWolf: "The Iberian Wolf (Canis lupus signatus) is found in the forests and mountains of Spain and Portugal. It primarily preys on deer and small mammals. Habitat destruction and hunting are the main threats to its survival. Conservation efforts focus on legal protection and awareness programs to reduce hunting. The population is estimated to be around 2,500 individuals.",
    greaterBambooLemur: "The Greater Bamboo Lemur (Prolemur simus) is critically endangered and found in the rainforests of Madagascar. It feeds almost exclusively on bamboo shoots. Habitat destruction is the primary threat to its survival. Conservation efforts focus on establishing protected areas and habitat restoration programs. The population is estimated to be around 500 individuals.",
    giantButterfly: "Queen Alexandra's Birdwing (Ornithoptera alexandrae) is the largest butterfly in the world, native to the rainforests of Papua New Guinea. It feeds on nectar from various rainforest plants. Habitat destruction and climate change are significant threats to its survival. Conservation efforts focus on habitat restoration and protecting rainforest ecosystems. The population size is currently unknown.",
    blueThroatedMacaw: "The Blue-Throated Macaw (Ara glaucogularis) is a critically endangered parrot species found in the rainforests of Bolivia. It primarily feeds on fruits and seeds. The illegal pet trade and habitat loss are major threats. Conservation actions include the creation of protected areas and captive breeding programs. The population is estimated to be around 450 individuals.",
    balkanLynx: "The Balkan Lynx (Lynx lynx balcanicus) is critically endangered and found in the mountain forests of the Balkans. It feeds on deer, small mammals, and birds. Hunting and habitat loss are significant threats. Conservation efforts include anti-poaching patrols and habitat protection. The population is estimated to be around 40 individuals.",
    scimitarHornedOryx: "The Scimitar-Horned Oryx (Oryx dammah) is a desert-dwelling antelope native to North Africa. It feeds on grasses and herbs. Overhunting and habitat destruction have led to its extinction in the wild, though reintroduction programs are underway. Conservation efforts focus on breeding programs and establishing protected areas. The population in the wild is estimated to be around 2,000 individuals.",
    darwinFrog: "Darwin's Frog (Rhinoderma darwinii) is a small frog species native to the temperate forests of Chile and Argentina. It feeds on insects and small invertebrates. Habitat loss and disease, particularly chytridiomycosis, are the main threats. Conservation efforts focus on creating protected areas and controlling disease outbreaks. The population is estimated to be around 1,000 individuals.",
    yellowFootedWallaby: "The Yellow-Footed Rock-Wallaby (Petrogale xanthopus) is a marsupial found in the rocky outcrops of Australia. It feeds primarily on grasses and herbs. Threats include habitat destruction and predation by introduced species such as foxes. Conservation efforts focus on predator control and habitat restoration. The population is estimated to be around 5,000 individuals.",
    galapagosPenguin: "The Galapagos Penguin (Spheniscus mendiculus) is the only penguin species found north of the equator, inhabiting the coastal areas of the Galapagos Islands. It feeds on fish and small crustaceans. Climate change and pollution are the primary threats. Conservation efforts focus on marine protection zones. The population is estimated to be around 2,000 individuals.",
    addraGazelle: "The Addra Gazelle (Nanger dama ruficollis), also known as the Dama Gazelle, inhabits the deserts of North Africa. It feeds on grasses and shrubs. Hunting and habitat loss have drastically reduced its numbers. Conservation actions focus on protected areas and breeding programs. The population is estimated to be around 500 individuals.",
    prairieChicken: "Attwater's Prairie Chicken (Tympanuchus cupido attwateri) is critically endangered and found in the coastal prairies of Texas. It feeds on insects and seeds. Habitat loss is the primary threat. Conservation efforts include habitat restoration and breeding programs. The population is estimated to be around 100 individuals.",
    hawaiianMonkSeal: "The Hawaiian Monk Seal (Neomonachus schauinslandi) is a critically endangered marine mammal native to the coastal waters of Hawaii. It feeds on fish and squid. Entanglement in fishing gear and habitat loss are significant threats. Conservation efforts focus on marine protection zones and bycatch reduction. The population is estimated to be around 1,400 individuals.",
    floridaPanther: "The Florida Panther (Puma concolor coryi) is critically endangered and found in the forests and swamps of Florida. It primarily feeds on deer and small mammals. Habitat loss and vehicle collisions are the primary threats. Conservation efforts focus on protected areas and wildlife crossings. The population is estimated to be around 230 individuals.",
    pygmyHippopotamus: "The Pygmy Hippopotamus (Choeropsis liberiensis) is a small, nocturnal hippo species found in the swamps and forests of West Africa. It feeds on grasses and leaves. Deforestation and poaching are significant threats. Conservation actions include protected areas and anti-poaching patrols. The population is estimated to be around 3,000 individuals.",
    spixMacaw: "Spix's Macaw (Cyanopsitta spixii) is critically endangered and found in the tropical forests of Brazil. It feeds on fruits and seeds. Habitat loss and the illegal pet trade are major threats. Conservation actions include captive breeding programs and reintroduction efforts. The population is estimated to be around 250 individuals.",
    antipodesParakeet: "The Antipodes Island Parakeet (Cyanoramphus unicolor) is native to the Antipodes Islands of New Zealand. It feeds on seeds and small invertebrates. Invasive species and habitat loss are significant threats. Conservation efforts focus on predator control and habitat restoration. The population is estimated to be around 200 individuals.",
    palawanPeacockPheasant: "The Palawan Peacock-Pheasant (Polyplectron napoleonis) is native to the forests of Palawan in the Philippines. It feeds on seeds and small invertebrates. Habitat loss and poaching are the main threats. Conservation efforts focus on protected areas and anti-poaching patrols. The population is estimated to be around 2,000 individuals.",
    mexicanGrayWolf: "The Mexican Gray Wolf (Canis lupus baileyi) is the smallest subspecies of gray wolf, found in the forests and deserts of Mexico and the southwestern US. It primarily feeds on deer and small mammals. Habitat loss and hunting are the main threats. Conservation efforts include reintroduction programs and the establishment of protected areas. The population is estimated to be around 200 individuals.",
    angelShark: "The Angel Shark (Squatina squatina) is critically endangered and found in the coastal waters of Europe and North Africa. It feeds on fish and crustaceans. Overfishing and habitat loss are the primary threats. Conservation efforts focus on establishing protected areas and implementing fishing regulations. The population is estimated to be around 1,000 individuals.",
    chineseGiantSalamander: "The Chinese Giant Salamander (Andrias davidianus) is the largest amphibian species, found in rivers and streams in China. It feeds on fish and insects. Pollution and habitat destruction are the main threats. Conservation efforts focus on captive breeding programs and habitat protection. The population is estimated to be around 5,000 individuals.",
    ethiopianHighlandWolf: "The Ethiopian Highland Wolf (Canis simensis) is critically endangered and found in the highlands of Ethiopia. It primarily feeds on rodents and small mammals. Habitat destruction and disease, particularly rabies, are major threats. Conservation efforts focus on vaccination programs and habitat protection. The population is estimated to be around 500 individuals.",
    laysanAlbatross: "The Laysan Albatross (Phoebastria immutabilis) is a large seabird found on islands in the Pacific Ocean. It primarily feeds on fish and squid. Pollution, especially plastic ingestion, is a significant threat. Conservation actions focus on marine protected areas and pollution control. The population is estimated to be around 10,000 individuals.",
    blackFacedSpoonbill: "The Black-Faced Spoonbill (Platalea minor) is a critically endangered wading bird found in coastal wetlands in East Asia. It feeds on fish and small invertebrates. Habitat loss and pollution are the primary threats. Conservation efforts focus on wetland restoration and habitat protection. The population is estimated to be around 4,000 individuals.",
    mountainNyala: "The Mountain Nyala (Tragelaphus buxtoni) is a large antelope species found in the mountains of Ethiopia. It feeds on grasses and shrubs. Hunting and habitat loss are the main threats. Conservation actions include protected areas and anti-poaching patrols. The population is estimated to be around 2,000 individuals.",
    markhor: "The Markhor (Capra falconeri) is a wild goat species native to the mountain ranges of Pakistan and Afghanistan. It feeds on grasses and leaves. Poaching and habitat loss are the main threats. Conservation efforts focus on the creation of protected areas and anti-poaching initiatives. The population is estimated to be around 2,500 individuals.",
    giantIbis: "The Giant Ibis (Thaumatibis gigantea) is critically endangered and found in the wetlands of Cambodia. It feeds on insects and small animals. Habitat destruction and hunting are significant threats. Conservation actions focus on wetland restoration and breeding programs. The population is estimated to be around 230 individuals.",
    yangtzeSoftshellTurtle: "The Yangtze Softshell Turtle (Rafetus swinhoei) is critically endangered and found in rivers in China and Vietnam. It feeds on fish and mollusks. Overfishing and habitat destruction are the main threats. Conservation efforts focus on captive breeding programs and habitat protection. Fewer than 3 individuals remain.",
    takahe: "The Takahe (Porphyrio hochstetteri) is a flightless bird native to the grasslands of New Zealand. It feeds on grasses and leaves. Habitat loss and introduced predators are major threats. Conservation actions include breeding programs and predator control efforts. The population is estimated to be around 400 individuals.",
    philippineTarsier: "The Philippine Tarsier (Carlito syrichta) is a small primate found in the rainforests of the Philippines. It feeds on insects and small vertebrates. Habitat destruction and the illegal pet trade are significant threats. Conservation efforts focus on protected areas and breeding programs. The population is estimated to be around 5,000 individuals.",
};


function NavBar() {
    return (
        <BrowserRouter>
            <>
                <div className='Nav'>
                    <hr />
                    <nav>
                        <Link to="/" className='link'>Homepage</Link>
                        <Link to="animals" className='link'>Catalogue</Link>
                        <Link to="random-fact" id='randomlink' className='link'>Random Fact</Link>
                    </nav>
                    <hr />
                </div>
                {/*Didnt had time for backend sorry for this mess and didnt used context api cuz there is no need and no need for complication*/}
                <Routes>
                    <Route path='/' element={<HomePage />} />
                    <Route path='animals' element={<AnimalCatalogue />} />
                    <Route path='random-fact' element={<RandomFact />} />

                    <Route path='animals/giant-panda' element={<Animal name="Giant Panda" src={giantPandaImage} desc={animalDesc.giantPanda} habitat="Bamboo forests in central China." diet="Primarily bamboo." threats="Habitat loss." curractions="Habitat restoration." whatcanyoudo="Support conservation." amount={1800} />} />
                    <Route path='animals/amur-leopard' element={<Animal name="Amur Leopard" src={amurLeopardImage} desc={animalDesc.amurLeopard} habitat="Forests in Russia and China." diet="Deer, hares." threats="Poaching." curractions="Anti-poaching patrols." whatcanyoudo="Support wildlife conservation." amount={100} />} />
                    <Route path='animals/snow-leopard' element={<Animal name="Snow Leopard" src={snowLeopardImage} desc={animalDesc.snowLeopard} habitat="Mountains of Central Asia." diet="Ungulates." threats="Poaching." curractions="Anti-poaching measures." whatcanyoudo="Support conservation efforts." amount={2500} />} />
                    <Route path='animals/black-rhino' element={<Animal name="Black Rhino" src={blackRhinoImage} desc={animalDesc.blackRhino} habitat="Africa." diet="Shrubs, trees." threats="Poaching." curractions="Anti-poaching patrols." whatcanyoudo="Support rhino conservation." amount={5000} />} />
                    <Route path='animals/orangutan' element={<Animal name="Orangutan" src={orangutanImage} desc={animalDesc.orangutan} habitat="Rainforests of Borneo and Sumatra." diet="Fruits, leaves." threats="Deforestation." curractions="Habitat protection." whatcanyoudo="Avoid deforestation." amount={14000} />} />
                    <Route path='animals/sea-turtle' element={<Animal name="Sea Turtle" src={seaTurtleImage} desc={animalDesc.seaTurtle} habitat="Oceans." diet="Jellyfish." threats="Pollution." curractions="Nesting site protection." whatcanyoudo="Reduce ocean pollution." amount={10000} />} />
                    <Route path='animals/vaquita' element={<Animal name="Vaquita" src={vaquitaImage} desc={animalDesc.vaquita} habitat="Gulf of California." diet="Small fish." threats="Fishing nets." curractions="Banning gillnets." whatcanyoudo="Support sustainable fishing." amount={10} />} />
                    <Route path='animals/saola' element={<Animal name="Saola" src={saolaImage} desc={animalDesc.saola} habitat="Vietnam and Laos." diet="Leaves." threats="Habitat loss." curractions="Anti-poaching measures." whatcanyoudo="Support forest conservation." amount={100} />} />
                    <Route path='animals/javan-rhino' element={<Animal name="Javan Rhino" src={javanRhinoImage} desc={animalDesc.javanRhino} habitat="Indonesia." diet="Leaves." threats="Natural disasters." curractions="Habitat protection." whatcanyoudo="Support habitat protection." amount={70} />} />
                    <Route path='animals/kakapo' element={<Animal name="Kakapo" src={kakapoImage} desc={animalDesc.kakapo} habitat="New Zealand." diet="Fruits, seeds." threats="Introduced predators." curractions="Breeding programs." whatcanyoudo="Support species recovery programs." amount={200} />} />

                    <Route path='animals/siberian-tiger' element={<Animal name="Siberian Tiger" src={siberianTigerImage} desc={animalDesc.siberianTiger} habitat="Russia." diet="Deer, wild boar." threats="Poaching." curractions="Anti-poaching laws." whatcanyoudo="Support tiger conservation." amount={500} />} />
                    <Route path='animals/blue-whale' element={<Animal name="Blue Whale" src={blueWhaleImage} desc={animalDesc.blueWhale} habitat="Oceans worldwide." diet="Krill." threats="Ship strikes." curractions="Marine protection zones." whatcanyoudo="Support ocean conservation." amount={2000} />} />
                    <Route path='animals/cheetah' element={<Animal name="Cheetah" src={cheetahImage} desc={animalDesc.cheetah} habitat="Savannas in Africa." diet="Gazelles." threats="Habitat fragmentation." curractions="Anti-poaching efforts." whatcanyoudo="Support habitat restoration." amount={7100} />} />
                    <Route path='animals/indian-elephant' element={<Animal name="Indian Elephant" src={elephantImage} desc={animalDesc.indianElephant} habitat="India and Southeast Asia." diet="Grasses, fruits." threats="Poaching." curractions="Conservation corridors." whatcanyoudo="Support elephant conservation." amount={20000} />} />
                    <Route path='animals/polar-bear' element={<Animal name="Polar Bear" src={polarBearImage} desc={animalDesc.polarBear} habitat="Arctic regions." diet="Seals, fish." threats="Climate change." curractions="Protecting Arctic habitats." whatcanyoudo="Reduce carbon footprint." amount={25000} />} />
                    <Route path='animals/red-panda' element={<Animal name="Red Panda" src={redPandaImage} desc={animalDesc.redPanda} habitat="Himalayas." diet="Bamboo." threats="Deforestation." curractions="Habitat restoration." whatcanyoudo="Support red panda conservation." amount={10000} />} />
                    <Route path='animals/green-sea-turtle' element={<Animal name="Green Sea Turtle" src={greenSeaTurtleImage} desc={animalDesc.greenSeaTurtle} habitat="Oceans." diet="Seagrass." threats="Pollution." curractions="Protecting nesting sites." whatcanyoudo="Reduce plastic use." amount={8500} />} />
                    <Route path='animals/pygmy-hippo' element={<Animal name="Pygmy Hippo" src={pygmyHippoImage} desc={animalDesc.pygmyHippo} habitat="West Africa." diet="Grasses, fruits." threats="Deforestation." curractions="Anti-poaching laws." whatcanyoudo="Support habitat conservation." amount={3000} />} />
                    <Route path='animals/african-wild-dog' element={<Animal name="African Wild Dog" src={wildDogImage} desc={animalDesc.africanWildDog} habitat="Africa." diet="Antelope, wildebeest." threats="Habitat fragmentation." curractions="Anti-poaching efforts." whatcanyoudo="Support conservation." amount={6600} />} />

                    <Route path='animals/iberian-lynx' element={<Animal name="Iberian Lynx" src={iberianLynxImage} desc={animalDesc.iberianLynx} habitat="Spain and Portugal." diet="Rabbits." threats="Habitat loss." curractions="Prey reintroduction." whatcanyoudo="Support lynx conservation." amount={400} />} />
                    <Route path='animals/galapagos-tortoise' element={<Animal name="Galapagos Tortoise" src={galapagosTortoiseImage} desc={animalDesc.galapagosTortoise} habitat="Galapagos Islands." diet="Grasses, cacti." threats="Invasive species." curractions="Invasive species control." whatcanyoudo="Support Galapagos conservation." amount={15000} />} />
                    <Route path='animals/tapanuli-orangutan' element={<Animal name="Tapanuli Orangutan" src={tapanuliOrangutanImage} desc={animalDesc.tapanuliOrangutan} habitat="Sumatra." diet="Fruits, leaves." threats="Deforestation." curractions="Anti-poaching patrols." whatcanyoudo="Support palm oil conservation." amount={800} />} />
                    <Route path='animals/hawksbill-turtle' element={<Animal name="Hawksbill Turtle" src={hawksbillTurtleImage} desc={animalDesc.hawksbillTurtle} habitat="Coral reefs." diet="Sponges, jellyfish." threats="Habitat destruction." curractions="Marine protection." whatcanyoudo="Support marine conservation." amount={25000} />} />
                    <Route path='animals/addax' element={<Animal name="Addax" src={addaxImage} desc={animalDesc.addax} habitat="Sahara Desert." diet="Grasses." threats="Poaching." curractions="Habitat protection." whatcanyoudo="Support desert conservation." amount={100} />} />
                    <Route path='animals/pygmy-three-toed-sloth' element={<Animal name="Pygmy Three-toed Sloth" src={pygmyThreeToedSlothImage} desc={animalDesc.pygmyThreeToedSloth} habitat="Mangroves in Panama." diet="Leaves." threats="Habitat loss." curractions="Eco-tourism management." whatcanyoudo="Support responsible tourism." amount={100} />} />
                    <Route path='animals/bactrian-camel' element={<Animal name="Wild Bactrian Camel" src={bactrianCamelImage} desc={animalDesc.bactrianCamel} habitat="Central Asia." diet="Grasses." threats="Habitat loss." curractions="Habitat protection." whatcanyoudo="Support camel conservation." amount={1000} />} />
                    <Route path='animals/siamese-crocodile' element={<Animal name="Siamese Crocodile" src={siameseCrocodileImage} desc={animalDesc.siameseCrocodile} habitat="Rivers in Southeast Asia." diet="Fish." threats="Poaching." curractions="Protected areas." whatcanyoudo="Support crocodile conservation." amount={250} />} />
                    <Route path='animals/saiga-antelope' element={<Animal name="Saiga Antelope" src={saigaImage} desc={animalDesc.saigaAntelope} habitat="Steppes in Central Asia." diet="Grasses." threats="Poaching." curractions="Anti-poaching efforts." whatcanyoudo="Support habitat restoration." amount={5000} />} />

                    <Route path='animals/scarlet-macaw' element={<Animal name="Scarlet Macaw" src={scarletMacawImage} desc={animalDesc.scarletMacaw} habitat="Rainforests in Central America." diet="Fruits, nuts." threats="Habitat loss." curractions="Habitat restoration." whatcanyoudo="Avoid exotic pets." amount={20000} />} />
                    <Route path='animals/tiger-quoll' element={<Animal name="Tiger Quoll" src={tigerQuollImage} desc={animalDesc.tigerQuoll} habitat="Australia." diet="Small mammals." threats="Invasive species." curractions="Predator control." whatcanyoudo="Support native species conservation." amount={500} />} />
                    <Route path='animals/japanese-crane' element={<Animal name="Japanese Crane" src={japaneseCraneImage} desc={animalDesc.japaneseCrane} habitat="Wetlands in Japan." diet="Fish, plants." threats="Habitat loss." curractions="Wetland restoration." whatcanyoudo="Support wetland conservation." amount={3000} />} />
                    <Route path='animals/dugong' element={<Animal name="Dugong" src={dugongImage} desc={animalDesc.dugong} habitat="Coastal waters." diet="Seagrass." threats="Habitat loss." curractions="Marine protection zones." whatcanyoudo="Support marine conservation." amount={85000} />} />
                    <Route path='animals/bonobo' element={<Animal name="Bonobo" src={bonoboImage} desc={animalDesc.bonobo} habitat="Congo Basin." diet="Fruits, leaves." threats="Poaching." curractions="Protected areas." whatcanyoudo="Support conservation efforts." amount={5000} />} />
                    <Route path='animals/andean-condor' element={<Animal name="Andean Condor" src={andeanCondorImage} desc={animalDesc.andeanCondor} habitat="South America." diet="Carrion." threats="Poisoning." curractions="Protected areas." whatcanyoudo="Avoid harmful chemicals." amount={6700} />} />
                    <Route path='animals/black-footed-ferret' element={<Animal name="Black-footed Ferret" src={blackFootedFerretImage} desc={animalDesc.blackFootedFerret} habitat="North America." diet="Prairie dogs." threats="Habitat loss." curractions="Habitat restoration." whatcanyoudo="Support prairie conservation." amount={500} />} />
                    <Route path='animals/leatherback-sea-turtle' element={<Animal name="Leatherback Sea Turtle" src={leatherbackSeaTurtleImage} desc={animalDesc.leatherbackSeaTurtle} habitat="Oceans." diet="Jellyfish." threats="Pollution." curractions="Nesting site protection." whatcanyoudo="Reduce plastic use." amount={34000} />} />
                    <Route path='animals/komodo-dragon' element={<Animal name="Komodo Dragon" src={komodoDragonImage} desc={animalDesc.komodoDragon} habitat="Indonesia." diet="Deer, pigs." threats="Habitat loss." curractions="Habitat protection." whatcanyoudo="Support wildlife conservation." amount={5000} />} />

                    <Route path='animals/sunda-tiger' element={<Animal name="Sunda Tiger" src={sundaTigerImage} desc={animalDesc.sundaTiger} habitat="Sumatra." diet="Deer, wild boar." threats="Poaching." curractions="Habitat protection." whatcanyoudo="Support tiger conservation." amount={400} />} />
                    <Route path='animals/sunda-clouded-leopard' element={<Animal name="Sunda Clouded Leopard" src={cloudedLeopardImage} desc={animalDesc.cloudedLeopard} habitat="Borneo." diet="Birds, small mammals." threats="Deforestation." curractions="Forest protection." whatcanyoudo="Support forest conservation." amount={10000} />} />
                    <Route path='animals/western-lowland-gorilla' element={<Animal name="Western Lowland Gorilla" src={gorillaImage} desc={animalDesc.westernLowlandGorilla} habitat="Central Africa." diet="Fruits, leaves." threats="Poaching." curractions="Protected areas." whatcanyoudo="Support gorilla conservation." amount={100000} />} />
                    <Route path='animals/indus-river-dolphin' element={<Animal name="Indus River Dolphin" src={indusRiverDolphinImage} desc={animalDesc.indusRiverDolphin} habitat="Indus River." diet="Fish." threats="Pollution." curractions="River protection." whatcanyoudo="Support river conservation." amount={1800} />} />
                    <Route path='animals/red-crowned-crane' element={<Animal name="Red-Crowned Crane" src={redCrownedCraneImage} desc={animalDesc.redCrownedCrane} habitat="Wetlands in East Asia." diet="Insects, fish." threats="Habitat loss." curractions="Wetland restoration." whatcanyoudo="Support wetland conservation." amount={3000} />} />
                    <Route path='animals/okapi' element={<Animal name="Okapi" src={okapiImage} desc={animalDesc.okapi} habitat="Rainforests of Congo." diet="Leaves, fruits." threats="Poaching." curractions="Anti-poaching patrols." whatcanyoudo="Support rainforest conservation." amount={3500} />} />
                    <Route path='animals/asiatic-lion' element={<Animal name="Asiatic Lion" src={asiaticLionImage} desc={animalDesc.asiaticLion} habitat="Forests of India." diet="Deer, antelope." threats="Habitat loss." curractions="Protected areas." whatcanyoudo="Support lion conservation." amount={600} />} />
                    <Route path='animals/yellow-eyed-penguin' element={<Animal name="Yellow-Eyed Penguin" src={yellowEyedPenguinImage} desc={animalDesc.yellowEyedPenguin} habitat="Coastal New Zealand." diet="Fish, squid." threats="Introduced predators." curractions="Habitat restoration." whatcanyoudo="Support penguin conservation." amount={4000} />} />
                    <Route path='animals/pygmy-marmoset' element={<Animal name="Pygmy Marmoset" src={marmosetImage} desc={animalDesc.pygmyMarmoset} habitat="Rainforests in South America." diet="Insects, fruits." threats="Habitat loss." curractions="Habitat protection." whatcanyoudo="Support forest conservation." amount={50000} />} />
                    <Route path='animals/pyrenean-ibex' element={<Animal name="Pyrenean Ibex" src={pyreneanIbexImage} desc={animalDesc.pyreneanIbex} habitat="Pyrenees mountains." diet="Grasses, herbs." threats="Overhunting, habitat loss." curractions="Extinct in the wild, cloning efforts." whatcanyoudo="Support biodiversity research." amount={0} />} />

                    <Route path='animals/bermuda-petrel' element={<Animal name="Bermuda Petrel" src={bermudaPetrelImage} desc={animalDesc.bermudaPetrel} habitat="Coastal Bermuda." diet="Fish, squid." threats="Habitat destruction, storms." curractions="Breeding programs, habitat restoration." whatcanyoudo="Support seabird conservation." amount={300} />} />
                    <Route path='animals/northern-white-rhino' element={<Animal name="Northern White Rhino" src={northernWhiteRhinoImage} desc={animalDesc.northernWhiteRhino} habitat="Grasslands of Central Africa." diet="Grass, leaves." threats="Poaching." curractions="Breeding programs, IVF efforts." whatcanyoudo="Support rhino conservation organizations." amount={2} />} />
                    <Route path='animals/baiji' element={<Animal name="Baiji (Yangtze River Dolphin)" src={baijiImage} desc={animalDesc.baiji} habitat="Yangtze River, China." diet="Fish." threats="Dams, pollution, ship traffic." curractions="Conservation efforts failed, likely extinct." whatcanyoudo="Support river conservation initiatives." amount={0} />} />
                    <Route path='animals/hirola' element={<Animal name="Hirola" src={hirolaImage} desc={animalDesc.hirola} habitat="African savannas." diet="Grasses." threats="Poaching, habitat loss." curractions="Protected areas, anti-poaching patrols." whatcanyoudo="Support wildlife conservation." amount={500} />} />
                    <Route path='animals/amadoni-wolf' element={<Animal name="Amadoni Wolf" src={amadoniWolfImage} desc={animalDesc.amadoniWolf} habitat="Brazilian savannas." diet="Small mammals, birds." threats="Habitat loss, hunting." curractions="Habitat protection, awareness programs." whatcanyoudo="Support wildlife protection efforts." amount={2500} />} />
                    <Route path='animals/giant-armadillo' element={<Animal name="Giant Armadillo" src={giantArmadilloImage} desc={animalDesc.giantArmadillo} habitat="Tropical forests of South America." diet="Insects, small animals." threats="Deforestation, hunting." curractions="Protected areas, habitat restoration." whatcanyoudo="Support conservation organizations." amount={1000} />} />
                    <Route path='animals/ili-pika' element={<Animal name="Ili Pika" src={iliPikaImage} desc={animalDesc.iliPika} habitat="Mountains of China." diet="Grasses, herbs." threats="Climate change, habitat loss." curractions="Monitoring, habitat protection." whatcanyoudo="Support climate action." amount={1000} />} />
                    <Route path='animals/ethiopian-wolf' element={<Animal name="Ethiopian Wolf" src={ethiopianWolfImage} desc={animalDesc.ethiopianWolf} habitat="Ethiopian highlands." diet="Rodents." threats="Habitat loss, disease." curractions="Vaccination campaigns, habitat protection." whatcanyoudo="Support Ethiopian wildlife conservation." amount={500} />} />
                    <Route path='animals/javan-slow-loris' element={<Animal name="Javan Slow Loris" src={javanSlowLorisImage} desc={animalDesc.javanSlowLoris} habitat="Tropical forests of Java." diet="Insects, fruits." threats="Pet trade, habitat loss." curractions="Anti-poaching measures, habitat restoration." whatcanyoudo="Avoid illegal wildlife products." amount={"unknown"} />} />
                    <Route path='animals/western-swamp-tortoise' element={<Animal name="Western Swamp Tortoise" src={westernSwampTortoiseImage} desc={animalDesc.westernSwampTortoise} habitat="Wetlands of Australia." diet="Aquatic plants, insects." threats="Habitat loss, climate change." curractions="Captive breeding, habitat restoration." whatcanyoudo="Support conservation programs." amount={50} />} />

                    <Route path='animals/madagascar-fish-eagle' element={<Animal name="Madagascar Fish Eagle" src={madagascarFishEagleImage} desc={animalDesc.madagascarFishEagle} habitat="Coastal wetlands of Madagascar." diet="Fish." threats="Habitat loss, human disturbance." curractions="Protected areas, awareness programs." whatcanyoudo="Support wetland conservation." amount={120} />} />
                    <Route path='animals/mountain-gorilla' element={<Animal name="Mountain Gorilla" src={mountainGorillaImage} desc={animalDesc.mountainGorilla} habitat="Montane forests of Central Africa." diet="Leaves, stems." threats="Poaching, habitat loss." curractions="Anti-poaching patrols, habitat protection." whatcanyoudo="Support wildlife organizations." amount={1000} />} />
                    <Route path='animals/ganges-river-dolphin' element={<Animal name="Ganges River Dolphin" src={gangesDolphinImage} desc={animalDesc.gangesDolphin} habitat="Ganges River, India." diet="Fish, crustaceans." threats="Pollution, fishing nets." curractions="River protection programs." whatcanyoudo="Support river conservation efforts." amount={3700} />} />
                    <Route path='animals/iberian-wolf' element={<Animal name="Iberian Wolf" src={iberianWolfImage} desc={animalDesc.iberianWolf} habitat="Spain and Portugal." diet="Deer, small mammals." threats="Hunting, habitat destruction." curractions="Legal protection, awareness programs." whatcanyoudo="Support wolf conservation." amount={2500} />} />
                    <Route path='animals/greater-bamboo-lemur' element={<Animal name="Greater Bamboo Lemur" src={greaterBambooLemurImage} desc={animalDesc.greaterBambooLemur} habitat="Madagascar rainforests." diet="Bamboo shoots." threats="Habitat destruction." curractions="Protected areas, habitat restoration." whatcanyoudo="Support lemur conservation." amount={500} />} />
                    <Route path='animals/giant-butterfly' element={<Animal name="Queen Alexandra's Birdwing" src={giantButterflyImage} desc={animalDesc.giantButterfly} habitat="Rainforests of Papua New Guinea." diet="Nectar." threats="Habitat destruction, climate change." curractions="Habitat restoration." whatcanyoudo="Support rainforest conservation." amount={"unknown"} />} />
                    <Route path='animals/blue-throated-macaw' element={<Animal name="Blue-Throated Macaw" src={blueThroatedMacawImage} desc={animalDesc.blueThroatedMacaw} habitat="Rainforests of Bolivia." diet="Fruits, seeds." threats="Illegal pet trade, habitat loss." curractions="Protected areas, breeding programs." whatcanyoudo="Avoid exotic pets." amount={450} />} />
                    <Route path='animals/balkan-lynx' element={<Animal name="Balkan Lynx" src={balkanLynxImage} desc={animalDesc.balkanLynx} habitat="Mountain forests in the Balkans." diet="Deer, small mammals." threats="Hunting, habitat loss." curractions="Anti-poaching patrols, habitat protection." whatcanyoudo="Support conservation programs." amount={40} />} />
                    <Route path='animals/scimitar-horned-oryx' element={<Animal name="Scimitar-Horned Oryx" src={oryxImage} desc={animalDesc.scimitarHornedOryx} habitat="Deserts of North Africa." diet="Grasses, herbs." threats="Hunting, habitat destruction." curractions="Reintroduction programs, protected areas." whatcanyoudo="Support wildlife conservation." amount={2000} />} />
                    <Route path='animals/darwin-frog' element={<Animal name="Darwin's Frog" src={darwinFrogImage} desc={animalDesc.darwinFrog} habitat="Temperate forests of Chile and Argentina." diet="Insects, small invertebrates." threats="Habitat loss, disease." curractions="Protected areas, disease control." whatcanyoudo="Support amphibian conservation." amount={1000} />} />

                    <Route path='animals/yellow-footed-rock-wallaby' element={<Animal name="Yellow-Footed Rock-Wallaby" src={yellowFootedWallabyImage} desc={animalDesc.yellowFootedWallaby} habitat="Rocky outcrops in Australia." diet="Grasses, herbs." threats="Habitat destruction, predation by introduced species." curractions="Predator control, habitat restoration." whatcanyoudo="Support wildlife conservation." amount={5000} />} />
                    <Route path='animals/galapagos-penguin' element={<Animal name="Galapagos Penguin" src={galapagosPenguinImage} desc={animalDesc.galapagosPenguin} habitat="Coastal areas of the Galapagos Islands." diet="Fish, small crustaceans." threats="Climate change, pollution." curractions="Marine protection zones." whatcanyoudo="Support marine conservation efforts." amount={2000} />} />
                    <Route path='animals/addra-gazelle' element={<Animal name="Addra Gazelle" src={addraGazelleImage} desc={animalDesc.addraGazelle} habitat="Deserts of North Africa." diet="Grasses, shrubs." threats="Hunting, habitat loss." curractions="Protected areas, breeding programs." whatcanyoudo="Support gazelle conservation." amount={500} />} />
                    <Route path='animals/attwaters-prairie-chicken' element={<Animal name="Attwater's Prairie Chicken" src={prairieChickenImage} desc={animalDesc.prairieChicken} habitat="Coastal prairies of Texas." diet="Insects, seeds." threats="Habitat loss." curractions="Habitat restoration, breeding programs." whatcanyoudo="Support habitat conservation." amount={100} />} />
                    <Route path='animals/hawaiian-monk-seal' element={<Animal name="Hawaiian Monk Seal" src={monkSealImage} desc={animalDesc.hawaiianMonkSeal} habitat="Coastal waters of Hawaii." diet="Fish, squid." threats="Entanglement in fishing gear, habitat loss." curractions="Marine protection zones, bycatch reduction efforts." whatcanyoudo="Support marine conservation." amount={1400} />} />
                    <Route path='animals/florida-panther' element={<Animal name="Florida Panther" src={floridaPantherImage} desc={animalDesc.floridaPanther} habitat="Forests and swamps of Florida." diet="Deer, small mammals." threats="Habitat loss, vehicle collisions." curractions="Protected areas, wildlife crossings." whatcanyoudo="Support panther conservation." amount={230} />} />
                    <Route path='animals/pygmy-hippopotamus' element={<Animal name="Pygmy Hippopotamus" src={pygmyHippoImage} desc={animalDesc.pygmyHippopotamus} habitat="Swamps and forests of West Africa." diet="Grasses, leaves." threats="Deforestation, poaching." curractions="Protected areas, anti-poaching patrols." whatcanyoudo="Support conservation efforts." amount={3000} />} />
                    <Route path='animals/sumatran-tiger' element={<Animal name="Sumatran Tiger" src={sumatranTigerImage} desc={animalDesc.sumatranTiger} habitat="Tropical forests of Sumatra." diet="Deer, wild boar." threats="Poaching, habitat loss." curractions="Anti-poaching patrols, protected areas." whatcanyoudo="Support tiger conservation." amount={400} />} />
                    <Route path='animals/spix-macaw' element={<Animal name="Spix's Macaw" src={spixMacawImage} desc={animalDesc.spixMacaw} habitat="Tropical forests of Brazil." diet="Fruits, seeds." threats="Habitat loss, illegal pet trade." curractions="Captive breeding programs, reintroduction." whatcanyoudo="Avoid illegal wildlife trade." amount={250} />} />
                    <Route path='animals/antipodes-island-parakeet' element={<Animal name="Antipodes Island Parakeet" src={antipodesParakeetImage} desc={animalDesc.antipodesParakeet} habitat="Antipodes Islands, New Zealand." diet="Seeds, small invertebrates." threats="Invasive species, habitat loss." curractions="Predator control, habitat restoration." whatcanyoudo="Support island restoration efforts." amount={200} />} />

                    <Route path='animals/palawan-peacock-pheasant' element={<Animal name="Palawan Peacock-Pheasant" src={palawanPeacockPheasantImage} desc={animalDesc.palawanPeacockPheasant} habitat="Forests of Palawan, Philippines." diet="Seeds, small invertebrates." threats="Habitat loss, poaching." curractions="Protected areas, anti-poaching patrols." whatcanyoudo="Support wildlife protection." amount={2000} />} />
                    <Route path='animals/mexican-gray-wolf' element={<Animal name="Mexican Gray Wolf" src={mexicanGrayWolfImage} desc={animalDesc.mexicanGrayWolf} habitat="Forests and deserts of Mexico and the Southwestern US." diet="Deer, small mammals." threats="Habitat loss, hunting." curractions="Reintroduction programs, protected areas." whatcanyoudo="Support wolf conservation efforts." amount={200} />} />
                    <Route path='animals/angel-shark' element={<Animal name="Angel Shark" src={angelSharkImage} desc={animalDesc.angelShark} habitat="Coastal waters of Europe and North Africa." diet="Fish, crustaceans." threats="Overfishing, habitat loss." curractions="Protected areas, fishing regulations." whatcanyoudo="Support sustainable fishing practices." amount={1000} />} />
                    <Route path='animals/chinese-giant-salamander' element={<Animal name="Chinese Giant Salamander" src={chineseGiantSalamanderImage} desc={animalDesc.chineseGiantSalamander} habitat="Rivers and streams in China." diet="Fish, insects." threats="Pollution, habitat destruction." curractions="Captive breeding, habitat protection." whatcanyoudo="Support freshwater habitat conservation." amount={5000} />} />
                    <Route path='animals/ethiopian-highland-wolf' element={<Animal name="Ethiopian Highland Wolf" src={ethiopianHighlandWolfImage} desc={animalDesc.ethiopianHighlandWolf} habitat="Highlands of Ethiopia." diet="Rodents, small mammals." threats="Habitat destruction, disease." curractions="Vaccination programs, habitat protection." whatcanyoudo="Support conservation programs in Ethiopia." amount={500} />} />
                    <Route path='animals/laysan-albatross' element={<Animal name="Laysan Albatross" src={laysanAlbatrossImage} desc={animalDesc.laysanAlbatross} habitat="Islands in the Pacific Ocean." diet="Fish, squid." threats="Pollution, plastic ingestion." curractions="Marine protected areas, pollution control." whatcanyoudo="Reduce plastic use, support ocean conservation." amount={10000} />} />
                    <Route path='animals/black-faced-spoonbill' element={<Animal name="Black-Faced Spoonbill" src={blackFacedSpoonbillImage} desc={animalDesc.blackFacedSpoonbill} habitat="Coastal wetlands in East Asia." diet="Fish, small invertebrates." threats="Habitat loss, pollution." curractions="Wetland restoration, habitat protection." whatcanyoudo="Support wetland conservation." amount={4000} />} />
                    <Route path='animals/mountain-nyala' element={<Animal name="Mountain Nyala" src={mountainNyalaImage} desc={animalDesc.mountainNyala} habitat="Mountains of Ethiopia." diet="Grasses, shrubs." threats="Hunting, habitat loss." curractions="Protected areas, anti-poaching patrols." whatcanyoudo="Support wildlife protection in Ethiopia." amount={2000} />} />
                    <Route path='animals/markhor' element={<Animal name="Markhor" src={markhorImage} desc={animalDesc.markhor} habitat="Mountain ranges of Pakistan and Afghanistan." diet="Grass, leaves." threats="Poaching, habitat loss." curractions="Protected areas, anti-poaching efforts." whatcanyoudo="Support wildlife conservation in Central Asia." amount={2500} />} />
                    <Route path='animals/giant-ibis' element={<Animal name="Giant Ibis" src={giantIbisImage} desc={animalDesc.giantIbis} habitat="Wetlands of Cambodia." diet="Insects, small animals." threats="Habitat destruction, hunting." curractions="Wetland restoration, breeding programs." whatcanyoudo="Support bird conservation efforts." amount={230} />} />
                    <Route path='animals/yangtze-softshell-turtle' element={<Animal name="Yangtze Softshell Turtle" src={yangtzeSoftshellTurtleImage} desc={animalDesc.yangtzeSoftshellTurtle} habitat="Rivers in China and Vietnam." diet="Fish, mollusks." threats="Overfishing, habitat destruction." curractions="Captive breeding, habitat protection." whatcanyoudo="Support freshwater conservation efforts." amount={3} />} />
                    <Route path='animals/takahe' element={<Animal name="Takahe" src={takaheImage} desc={animalDesc.takahe} habitat="Grasslands of New Zealand." diet="Grasses, leaves." threats="Habitat loss, introduced predators." curractions="Breeding programs, predator control." whatcanyoudo="Support conservation efforts in New Zealand." amount={400} />} />
                    <Route path='animals/philippine-tarsier' element={<Animal name="Philippine Tarsier" src={philippineTarsierImage} desc={animalDesc.philippineTarsier} habitat="Rainforests of the Philippines." diet="Insects, small vertebrates." threats="Habitat destruction, pet trade." curractions="Protected areas, breeding programs." whatcanyoudo="Support wildlife conservation, avoid illegal pet trade." amount={5000} />} />
                </Routes>
            </>
        </BrowserRouter>
    );
}

export default NavBar;
