import React, { useRef } from 'react';
import { Route, Routes, Link, BrowserRouter } from 'react-router-dom';
import HomePage from './HomePage';
import TipCatalogue from './TipCatalogue';
import Tip from './Tip';
import Best4u from './Best4u';
import tip1img from "./Images/tip_1.png"
import tip2img from "./Images/tip_2.png"
import tip3img from "./Images/tip_3.png"
import tip4img from "./Images/tip_4.png"
import tip5img from "./Images/tip_5.png"
import tip6img from "./Images/tip_6.png"
import tip7img from "./Images/tip_7.png"
import tip8img from "./Images/tip_8.png"
import tip9img from "./Images/tip_9.png"
import tip10img from "./Images/tip_10.png"


const tip_1List = {
    "Set Up a Composting Area": "Identify a suitable space on your farm for composting. This area should be shaded and well-drained. You can use compost bins, piles, or dedicated pits depending on the size of your farm. Ensure it’s close to your fields but away from water sources to prevent runoff.",
    "Collect Organic Waste": "Gather organic waste from your farm and household, including crop residues, manure, food scraps, and leaves. It’s essential to have a balanced mix of nitrogen-rich materials (green waste like vegetable scraps and manure) and carbon-rich materials (brown waste like straw, wood chips, or dry leaves) to speed up the composting process.",
    "Build Your Compost Pile": "Start layering the compost pile by alternating green and brown materials. Aim for a ratio of 2:1 (two parts carbon to one part nitrogen). Keep the pile moist but not soggy—similar to the dampness of a wrung-out sponge. Aerate the compost regularly by turning it with a pitchfork or compost aerator to ensure oxygen flow, which helps decompose the materials efficiently.",
    "Let It Decompose": "Allow the compost pile to decompose for several months. Depending on conditions like weather, material type, and how often you turn the pile, the compost can take anywhere from three months to a year to fully break down. Monitor the temperature and moisture levels to ensure proper decomposition.",
    "Apply the Finished Compost": "Once the compost is dark, crumbly, and has an earthy smell, it’s ready to be used. Spread the finished compost on your fields to improve soil structure, increase its organic matter content, and enhance its ability to retain water. Compost acts as a slow-release fertilizer, providing essential nutrients for crop growth without the risk of chemical runoff."
}
const tip_2List = {
    "Assess Your Farm’s Energy Needs": "Before transitioning to renewable energy, it's important to calculate your farm's energy usage. Identify which operations require the most energy, such as irrigation systems, machinery, lighting, or storage facilities. This will help you estimate the renewable energy capacity required.",
    "Choose the Right Renewable Energy Source": "Evaluate your farm’s location and available resources to choose the most suitable renewable energy source: Solar Power: Ideal for sunny regions with plenty of daylight. Wind Power: Suitable for areas with consistent wind speeds. Hydropower: If your farm has access to flowing water, micro-hydro turbines can be an efficient energy source.",
    "Plan the Installation": "Once you've selected your renewable energy source, work with experts to plan the installation of equipment like solar panels or wind turbines. Ensure you have enough space on rooftops or open fields for installation. Check for any local permits or regulations needed for installing renewable energy systems.",
    "Integrate with Farm Operations": "Connect the renewable energy system to your farm’s operations. Solar panels can power irrigation pumps, greenhouse lighting, or cold storage units, while wind turbines can supply electricity to barns and processing equipment. Consider integrating energy storage solutions like batteries to store excess energy for later use.",
    "Monitor and Maintain the System": "Once your system is installed, regularly monitor its performance. Use energy tracking software to assess efficiency and track savings. Maintenance, such as cleaning solar panels or inspecting wind turbines, is critical to ensure the system runs efficiently for many years."
}
const tip_3List = {
    "Install Drip Irrigation Systems": "Drip irrigation is one of the most efficient methods to water crops. It delivers water directly to the roots of the plants through a network of tubes, reducing water waste due to evaporation or runoff. Begin by assessing your farm's layout and the types of crops you grow to design a suitable drip irrigation system. Make sure to install filters to prevent clogging in the tubes.",
    "Harvest Rainwater": "Set up rainwater harvesting systems to collect and store rainwater. This can be done by installing gutters on barns, greenhouses, and other buildings, channeling the water into storage tanks. Rainwater can be used during dry periods to irrigate crops or fill livestock troughs, significantly reducing dependence on groundwater or municipal supplies.",
    "Monitor Soil Moisture Levels": "Use soil moisture sensors to monitor the moisture levels in your fields. This allows you to irrigate only when necessary, avoiding overwatering. Soil sensors can be placed in key areas of the farm to provide real-time data on how much water is needed, helping to optimize water use and improve crop yields.",
    "Mulch Crops": "Mulching is another great way to conserve water. Apply organic materials like straw, leaves, or wood chips to the soil surface to reduce evaporation and keep the soil cooler. Mulch also helps suppress weeds, which can compete with crops for water. This simple method can significantly reduce the amount of water your crops need.",
    "Use Drought-Tolerant Crops": "In regions with limited water resources, consider planting drought-tolerant crops or varieties that require less water. These crops are bred to withstand dry conditions and require less frequent irrigation, making them an ideal choice for water conservation strategies."
}
const tip_4List = {
    "Assess Your Farm’s Layout": "Evaluate your farm’s land layout to identify areas where trees can be integrated into crop fields or pastures. Focus on sections of the farm that could benefit from shade, erosion control, or additional biodiversity. Consider boundaries, buffer zones, and open spaces as areas for potential tree planting.",
    "Choose the Right Trees": "Select tree species that are suitable for your climate and farm conditions. It’s important to choose native species that support local biodiversity. Trees with deep root systems, such as leguminous trees, can help improve soil fertility by fixing nitrogen. Fruit trees or nut-bearing species can also provide additional economic benefits.",
    "Plan Tree Spacing and Placement": "Carefully plan the spacing between trees to ensure they don’t compete with crops or livestock. Trees should be spaced wide enough to allow sufficient light and air to reach the crops, but close enough to provide shade and protection. In silvopasture systems, trees can be planted in rows across pastures, providing shade for animals.",
    "Implement a Management Plan": "Agroforestry requires ongoing management to ensure the trees and crops coexist harmoniously. Regular pruning, thinning, and monitoring of tree health are crucial to prevent competition between trees and crops. Make sure to manage livestock grazing around young trees to prevent damage.",
    "Track Environmental and Economic Benefits": "Over time, monitor the benefits that agroforestry brings to your farm. These can include improved soil health, increased biodiversity, reduced soil erosion, and better water retention. In some cases, trees may offer an additional revenue stream through the sale of timber, fruits, or nuts, contributing to the farm’s economic sustainability."
}
const tip_5List = {
    "Plan Crop Rotations": "Begin by organizing a plan for rotating crops in different fields over multiple growing seasons. Crop rotation helps break the cycle of pests and diseases by varying the type of crops grown in the same field each year. For example, legumes (which fix nitrogen) can be followed by nutrient-demanding crops like corn or wheat. Design a schedule that ensures each section of your farm is planted with a different type of crop each season.",
    "Select Complementary Crops for Companion Planting": "Choose crops that can be planted together for mutual benefit. Some plants improve the growth of others by attracting beneficial insects or repelling pests, while others enhance nutrient uptake. For example, planting beans with corn allows beans to fix nitrogen, benefiting the nutrient-heavy corn. Make a list of crops that work well together and plan how to pair them.",
    "Implement Companion Planting in Rows or Blocks": "Once you've selected your companion plants, implement the system by planting them in adjacent rows or interspersing them within the same field. Make sure each crop has enough space and resources. For example, taller crops like corn can provide shade for smaller plants like lettuce, and shallow-rooted plants can be paired with deeper-rooted crops to maximize soil usage.",
    "Monitor Soil Health": "As crop rotation and companion planting improve soil fertility over time, regularly monitor soil quality and nutrient levels. Use soil tests to check for improvements in nitrogen, phosphorus, and organic matter. Adjust your rotation plan or companion planting arrangements as needed based on the results.",
    "Manage Pests and Diseases": "One of the key benefits of crop rotation and companion planting is natural pest control. By varying crops and using pest-repelling companion plants (like marigolds), you reduce the need for chemical pesticides. Regularly inspect crops for signs of pests or diseases and adjust your planting strategy to minimize risk."
}
const tip_6List = {
    "Identify Beneficial Insects": "Begin by identifying beneficial insects that naturally prey on harmful pests. Common examples include ladybugs, which eat aphids, and lacewings, which feed on caterpillars and other pests. Research which beneficial insects are most effective for the crops you grow and the common pests in your area.",
    "Plant Pest-Repelling Crops": "Incorporate pest-repellent plants like marigolds, basil, and garlic into your crop fields. These plants naturally deter many common pests such as aphids, whiteflies, and mosquitoes. Strategically planting these crops between rows of your main crops can reduce the presence of pests without relying on chemical pesticides.",
    "Build Habitats for Beneficial Insects": "To encourage beneficial insects to stay on your farm, create habitats that provide them with shelter and food. Install insect hotels, plant diverse crops, and leave areas with native plants and flowers that support a variety of insects. This encourages natural predators to establish themselves in your fields.",
    "Monitor Pest Levels": "Regularly inspect your crops for signs of pest infestations and the presence of beneficial insects. Use natural methods, such as introducing more beneficial insects or applying organic insecticidal soap, to control outbreaks before they get severe.",
    "Rotate Pest Control Strategies": "To prevent pests from developing resistance to any one method, rotate different pest control strategies throughout the growing season. Use a combination of natural predators, pest-repelling plants, and organic treatments to keep pest levels in check.",
}
const tip_7List = {
    "Transition to Organic Inputs": "Begin by phasing out synthetic fertilizers and pesticides, replacing them with organic alternatives. Organic fertilizers, such as compost and manure, provide essential nutrients while improving soil health. Organic-approved pest control methods, such as neem oil or diatomaceous earth, can help manage pest problems without harmful chemicals.",
    "Build Soil Fertility Naturally": "In organic farming, the focus is on building healthy, fertile soil through natural means. Incorporate crop rotation, cover crops, and green manures to increase soil organic matter and nutrient content. This enhances the soil’s structure, water retention, and nutrient-holding capacity, reducing the need for external inputs.",
    "Use Organic Pest and Weed Control": "Organic farming discourages the use of synthetic chemicals. Instead, control weeds using mulch, cover crops, and manual removal. Manage pests through natural pest control methods, such as beneficial insects and biological treatments like Bacillus thuringiensis (Bt), a naturally occurring bacterium that targets specific pests.",
    "Maintain Organic Certification Standards": "If you plan to sell certified organic products, follow the standards set by organic certification bodies. This involves regular inspections, maintaining detailed records of inputs and practices, and ensuring that no prohibited substances are used.",
    "Market Organic Produce": "Leverage the growing demand for organic products by marketing your farm’s organic status. Highlight the environmental and health benefits of organic farming to attract conscious consumers, local markets, or organic wholesalers."
}
const tip_8List = {
    "Minimize Soil Disturbance": "In reduced tillage farming, aim to disturb the soil as little as possible. Use tools like strip-tillers or specialized no-till drills to plant seeds directly into the soil without plowing or turning the earth. This helps maintain soil structure and organic matter.",
    "Grow Cover Crops": "Cover crops, such as clover, rye, or vetch, protect the soil from erosion and improve fertility during off-seasons. They add organic matter to the soil and reduce the need for tilling by suppressing weeds naturally.",
    "Rotate Crops and Use Mulch": "Rotate crops annually and use organic mulch to suppress weeds and retain soil moisture. Mulch and crop residue left on the surface of the field break down over time, adding nutrients to the soil without the need for tillage.",
    "Monitor Soil Health": "Regularly test your soil to track improvements in structure, fertility, and moisture retention. Reduced tillage encourages beneficial soil organisms, such as earthworms and fungi, which improve soil health. Adjust your practices based on the results to continue building healthy soil.",
    "Manage Equipment": "Ensure your equipment is adapted for reduced tillage. Specialized no-till planters and strip-tillers can seed directly into crop residue, minimizing soil disturbance. Properly maintained equipment ensures the success of your reduced-tillage farming practices."
}
const tip_9List = {
    "Plant Pollinator-Friendly Plants": "Start by planting a variety of wildflowers, herbs, and native plants around your crop fields to attract beneficial pollinators like bees and butterflies. Choose plants that bloom at different times to provide pollinators with a constant food source throughout the growing season.",
    "Diversify Crops": "Grow a variety of crops on your farm rather than focusing on monoculture. Diverse cropping systems improve soil health, reduce pest pressure, and support different types of beneficial organisms. Rotate crops annually to ensure that the soil remains fertile and to disrupt pest cycles.",
    "Build Habitats for Wildlife": "Designate parts of your farm for wildlife habitats, such as hedgerows, windbreaks, or ponds. These areas provide shelter and food for birds, beneficial insects, and small mammals, creating a balanced ecosystem that benefits crop production.",
    "Use Integrated Pest Management (IPM)": "Implement Integrated Pest Management techniques to promote a healthy, diverse environment. This involves combining biological controls, such as beneficial insects, with cultural practices like crop rotation to manage pests without harming non-target species.",
    "Reduce Chemical Inputs": "Minimize the use of synthetic pesticides and fertilizers, as these chemicals can harm beneficial organisms and reduce biodiversity. Focus on natural alternatives, such as compost, organic fertilizers, and biological pest control, to maintain a healthy ecosystem.",
}
const tip_10List = {
    "Invest in Soil Moisture Sensors": "Install soil moisture sensors throughout your fields to monitor the moisture levels in the soil. These sensors provide real-time data, helping farmers decide when and how much to irrigate. This reduces water waste and ensures crops receive the optimal amount of water for growth.",
    "Use GPS-Guided Tractors": "Implement GPS-guided tractors to improve planting, tilling, and harvesting accuracy. These tractors use GPS technology to ensure precise field operations, minimizing overlaps and gaps, which improves efficiency and reduces fuel usage.",
    "Adopt Drones for Crop Monitoring": "Use drones to monitor crop health from above. Drones equipped with infrared cameras can detect signs of disease, nutrient deficiencies, or water stress, allowing farmers to take corrective action before problems spread. This technology helps farmers optimize yields and reduce crop losses.",
    "Utilize Farm Management Software": "Adopt farm management software to track planting schedules, monitor crop growth, and manage resources. This software integrates data from sensors, GPS systems, and drones, allowing farmers to make data-driven decisions that improve productivity and sustainability.",
    "Embrace Precision Agriculture": "Precision agriculture uses data-driven techniques to optimize farming practices. Farmers can apply fertilizers and pesticides more efficiently based on soil and plant health data. This not only improves crop yields but also reduces environmental impact by minimizing excess inputs."
}

const descriptions = [
    "Composting is a natural and effective way to recycle organic farm waste into nutrient-rich fertilizer that improves soil health. By setting up a dedicated composting area on your farm, you can turn materials like crop residues, manure, and food scraps into valuable compost. The process involves layering green and brown materials in the compost pile, maintaining the right moisture levels, and regularly turning the pile to facilitate aerobic decomposition. This balance of nitrogen-rich and carbon-rich materials is key to producing high-quality compost that breaks down efficiently.Over several months, the organic matter in the pile decomposes into a dark, crumbly material that is rich in essential nutrients like nitrogen, phosphorus, and potassium. Once ready, compost can be spread over crop fields to enhance soil fertility and improve its structure, increasing its capacity to hold water and support plant growth. Unlike chemical fertilizers, compost releases nutrients slowly over time, reducing the risk of nutrient runoff and promoting long-term soil health. By embracing composting, farmers can reduce waste, cut down on chemical fertilizer costs, and build a more sustainable farming system",
    "Transitioning to renewable energy on a farm not only reduces dependence on fossil fuels but also leads to long-term cost savings and environmental benefits. One of the most widely adopted renewable energy sources is solar power, which is ideal for sunny regions. Solar panels can be installed on rooftops or in open fields, generating electricity to power various farm operations like irrigation systems, greenhouses, and storage facilities. Another viable option is wind energy, especially for farms located in areas with consistent wind speeds. Wind turbines can supply electricity for heavy machinery and barns, helping to lower operational costs.Additionally, hydropower may be suitable for farms with access to flowing water, where micro-hydro turbines can generate energy sustainably. Regardless of the energy source, it’s essential to start by assessing your farm’s energy needs and planning accordingly. Proper integration into the farm’s electrical systems, along with energy storage options like batteries, can ensure uninterrupted power supply even on cloudy or windless days. Monitoring and maintaining the renewable energy systems are crucial for maximizing efficiency and ensuring they continue to perform over time. Farmers who adopt renewable energy not only contribute to a greener environment but also position their farms to thrive in the face of rising energy costs.",
    "Water conservation is crucial for sustainable farming, especially in regions prone to drought or limited water availability. One of the most effective ways to reduce water waste is by using drip irrigation systems. These systems deliver water directly to the roots of plants, minimizing evaporation and ensuring crops receive just the right amount of water. Alongside drip irrigation, rainwater harvesting is another essential practice. Farmers can install gutters on barns or greenhouses to collect rainwater, storing it in tanks for use during dry periods. This reduces reliance on groundwater or external water supplies, making the farm more resilient to water shortages. In addition to efficient irrigation systems, farmers can utilize soil moisture sensors to monitor real-time moisture levels in their fields. This technology ensures that crops are watered only when necessary, preventing over-irrigation and optimizing water use. Mulching is another simple but effective water conservation method. By applying organic mulch around crops, farmers can reduce water evaporation from the soil, keeping it cooler and helping it retain moisture for longer. Additionally, choosing drought-tolerant crops that require less water can further enhance water efficiency, ensuring the farm remains productive even in challenging climates. Overall, these strategies empower farmers to use water wisely, preserve natural resources, and increase crop resilience.",
    "Agroforestry is a powerful technique that integrates trees into agricultural systems, promoting both environmental sustainability and farm productivity. By incorporating trees into crop fields or pastures, farmers can improve soil health, reduce erosion, and enhance biodiversity. The key to successful agroforestry is selecting the right tree species for the specific climate and farm conditions. Native species are often the best choice, as they support local ecosystems and tend to be more resilient. Trees with deep root systems, such as nitrogen-fixing legumes, can also improve soil fertility, benefiting nearby crops. Proper tree placement is essential to ensure that the trees provide shade and protection without competing with crops or livestock for light, water, and nutrients. For example, in silvopasture systems, rows of trees can be planted across pastures, providing shade for livestock, which improves their health and well-being. Once established, agroforestry systems require regular management, including pruning and thinning, to maintain the balance between trees and crops. Over time, the benefits of agroforestry become clear—healthier soils, increased biodiversity, and even the potential for additional income from timber, fruits, or nuts. As a long-term investment, agroforestry helps build resilience in the face of environmental changes, making farms more sustainable and productive.",
    "Crop rotation and companion planting are time-tested techniques that boost soil health, manage pests, and increase overall crop yields. Crop rotation involves systematically alternating different crops in the same field across multiple growing seasons. This breaks pest and disease cycles and ensures that soil nutrients are replenished naturally. For instance, rotating nitrogen-fixing legumes like beans or peas with nutrient-demanding crops like corn or wheat is an excellent way to maintain soil fertility without heavy reliance on chemical fertilizers. A well-planned crop rotation system leads to healthier, more productive soil over the long term. Companion planting complements this system by placing plants with mutually beneficial properties together. Some plants, like marigolds, repel pests, while others, like beans, enrich the soil with essential nutrients that neighboring crops can use. For example, corn and beans are a classic companion planting pair—corn provides a natural trellis for climbing beans, while beans fix nitrogen in the soil, benefiting the corn. Additionally, mixing crops with different root depths allows them to draw nutrients and water from different layers of the soil, maximizing efficiency. By integrating crop rotation and companion planting, farmers can create resilient, sustainable agricultural systems that boost yields while protecting soil health.",
    "Natural pest control is a cornerstone of sustainable farming, allowing farmers to protect their crops without relying on chemical pesticides. By encouraging beneficial insects such as ladybugs, lacewings, and hoverflies, farmers can establish a natural predator-prey balance in their fields. Ladybugs, for example, are voracious predators of aphids, which can otherwise cause significant damage to crops. To support these beneficial insects, farmers can plant diverse flowering plants that provide habitat and food, creating a more welcoming environment for these natural allies. In addition to utilizing insect predators, farmers can plant pest-repellent crops like marigolds, basil, and garlic between rows of crops to deter common pests. Marigolds, for instance, emit a scent that repels nematodes and whiteflies. Combining this approach with insect hotels and natural habitats helps ensure a healthy population of beneficial insects that can control pests throughout the growing season. Regularly monitoring fields for pest populations and rotating pest control methods helps prevent outbreaks and reduces the need for chemical intervention. By embracing natural pest control, farmers can protect their crops, promote biodiversity, and create a more resilient agricultural system.",
    "Organic farming is based on the principle of working in harmony with nature to cultivate crops and raise livestock. This method prioritizes soil health, biodiversity, and the reduction of harmful chemicals, making it a sustainable alternative to conventional farming. Organic farmers rely on natural inputs, such as compost, manure, and cover crops, to build soil fertility. This not only provides essential nutrients for crops but also improves soil structure, helping it retain water and resist erosion. Organic pest and weed control measures focus on natural solutions like beneficial insects, crop rotation, and biological treatments, all of which reduce the need for synthetic pesticides and herbicides. Transitioning to organic farming requires commitment to strict standards if the goal is certification. Farmers must ensure that no prohibited chemicals are used on their fields and that organic practices are consistently applied. The payoff for this effort is not only healthier soil and crops but also access to growing markets that value organic products. Consumers are increasingly interested in organic foods due to concerns over pesticide residues and environmental impact, making organic farming both a sustainable and profitable approach.",
    "Reduced tillage farming is an environmentally friendly approach that focuses on minimizing soil disturbance to maintain soil health and structure. Traditional plowing can lead to soil erosion and the loss of organic matter, whereas reduced tillage methods, such as no-till or strip-till, protect the soil by planting seeds directly into undisturbed earth. This practice preserves the soil’s ability to retain moisture, supports the development of beneficial organisms like earthworms, and reduces the need for chemical inputs. By growing cover crops in the off-season, farmers can further protect the soil from erosion, suppress weeds, and improve nutrient cycling. These cover crops also reduce the need for tilling, as they break down naturally, adding organic matter to the soil. Additionally, the use of organic mulch keeps the soil cool, moist, and fertile, reducing the reliance on external fertilizers. Regular soil health monitoring is essential to track improvements and adjust practices as needed. Through reduced tillage, farmers can promote long-term soil health while decreasing the labor and energy costs associated with conventional plowing methods.",
    "Enhancing biodiversity on farms is essential for creating a balanced and resilient ecosystem that supports both crop production and environmental health. One of the simplest ways to boost biodiversity is by planting pollinator-friendly plants around crop fields. These plants attract beneficial pollinators like bees and butterflies, which are vital for crop pollination and yield. By choosing a diverse range of plants that bloom at different times, farmers can ensure that pollinators have a steady food supply throughout the year. In addition to flowers, farmers can diversify their crops, rotating different varieties to improve soil health, disrupt pest cycles, and reduce the risk of crop failure. Designating areas of the farm as wildlife habitats, such as hedgerows or ponds, provides shelter and food for birds, insects, and small mammals. These habitats encourage the presence of beneficial organisms that control pests naturally, reducing the need for chemical inputs. Integrated Pest Management (IPM) strategies further promote biodiversity by combining natural pest control methods with crop rotation and careful monitoring. As biodiversity increases, the farm becomes more self-sustaining, with fewer pests, healthier soil, and improved crop resilience. By enhancing biodiversity, farmers create a thriving ecosystem that benefits both agriculture and the environment.",
    "Smart farming technology is revolutionizing agriculture by enabling farmers to optimize productivity while conserving resources. Soil moisture sensors provide real-time data on soil moisture levels, ensuring that irrigation is applied only when needed, reducing water waste and preventing over-irrigation. Meanwhile, GPS-guided tractors improve the accuracy of planting, tilling, and harvesting operations, minimizing overlaps and saving fuel. These tools allow farmers to manage their fields with precision, enhancing both efficiency and sustainability. Additionally, drones equipped with infrared cameras offer a bird’s-eye view of crop health, enabling farmers to detect issues like nutrient deficiencies or water stress early on. This helps farmers take targeted action, reducing the risk of crop loss. The integration of data through farm management software allows for better decision-making, enabling farmers to plan planting schedules, track resource usage, and monitor crop growth in real time. By embracing precision agriculture, farmers can apply inputs like fertilizers and pesticides more efficiently, minimizing waste and environmental impact. Smart farming technology empowers farmers to make informed decisions, reduce costs, and increase yields, all while contributing to a more sustainable agricultural system."
]
function NavBar() {
    const navRef = useRef()
    return (
        <BrowserRouter>
            <>
                <div className='Nav' ref={navRef}>
                    <nav>
                        <Link to="/" className='link'>Homepage</Link>
                        <Link to="tips" className='link'>Tips</Link>
                        <Link to="test" className='link' id='testLink'>Test</Link>
                    </nav>
                    <hr></hr>
                </div>
                <Routes>
                    <Route path='/' element={<HomePage />} />
                    <Route path='tips' element={<TipCatalogue />} />
                    <Route path='test' element={<Best4u scrollRef={navRef} />} />
                    <Route path='tips/composting-and-organic-fertilizers' element={<Tip steps={tip_1List} desc={descriptions[0]} img={tip1img} name="Composting and Organic Fertilizers" />}></Route>
                    <Route path='tips/renewable-energy-on-farms' element={<Tip steps={tip_2List} desc={descriptions[1]} name="Renewable Energy on Farms" img={tip2img} />}></Route>
                    <Route path='tips/water-conservation-on-farms' element={<Tip steps={tip_3List} desc={descriptions[2]} name="Water Conservation on Farms" img={tip3img} />}></Route>
                    <Route path='tips/agroforestry-on-farms' element={<Tip steps={tip_4List} desc={descriptions[3]} name="Agroforestry on Farms" img={tip4img} />}  ></Route>
                    <Route path='tips/crop-rotation-and-companion-planting' element={<Tip steps={tip_5List} desc={descriptions[4]} name="Crop Rotation and Companion Planting" img={tip5img} />}></Route>
                    <Route path='tips/natural-pest-control-on-farms' element={<Tip steps={tip_6List} desc={descriptions[5]} name="Natural Pest Control on Farms" img={tip6img} />}></Route>
                    <Route path='tips/practicing-organic-farming' element={<Tip steps={tip_7List} desc={descriptions[6]} name="Practicing Organic Farming" img={tip7img} />}></Route>
                    <Route path='tips/reduced-tillage-farming' element={<Tip steps={tip_8List} desc={descriptions[7]} name="Reduced Tillage Farming" img={tip8img} />}></Route>
                    <Route path='tips/biodiversity-enhancement' element={<Tip steps={tip_9List} desc={descriptions[8]} name="Biodiversity Enhancement" img={tip9img} />}></Route>
                    <Route path='tips/smart-farming-technology' element={<Tip steps={tip_10List} desc={descriptions[9]} name="Smart Farming Technology" img={tip10img} />}></Route>
                </Routes>
            </>
        </BrowserRouter>
    );
}

export default NavBar;
