import { useState } from "react";
import React from 'react'


function RandomFact() {
    const facts = [
        "The axolotl can regenerate its heart, brain, and spinal cord.",
        "Hummingbirds are the only birds that can fly backwards.",
        "A giraffe’s neck is too short to reach the ground, so it has to spread its legs to drink water.",
        "Elephants are known to mourn their dead and have been observed touching and caressing the bones of deceased elephants.",
        "The mantis shrimp has the most complex visual system in the animal kingdom, with 16 types of color receptors.",
        "The platypus is one of the few mammals that lay eggs and produces venom.",
        "A single honeybee can visit up to 5,000 flowers in a single day.",
        "Cuttlefish have three hearts and blue blood.",
        "The African elephant’s ears can grow up to 6 feet long and help regulate their body temperature.",
        "The cheetah is capable of reaching speeds of up to 75 miles per hour.",
        "A group of owls is known as a 'parliament.'",
        "The blue whale’s heart is as large as a small car.",
        "The largest mammal on Earth is the blue whale, which can weigh up to 200 tons.",
        "A group of jellyfish is called a 'smack.'",
        "The starfish can regenerate lost arms and, in some cases, an entire new starfish from a single arm.",
        "The bongo, a large antelope, has a beautiful reddish-brown coat with white stripes.",
        "The giant squid has the largest eyes of any animal, measuring up to 10 inches in diameter.",
        "The Arctic Tern has the longest migration of any animal, traveling up to 71,000 kilometers annually.",
        "A lion’s roar can be heard from up to 5 miles away.",
        "Dolphins use echolocation to navigate and find food in the dark.",
        "The heart of a blue whale is so large that a human could crawl through its arteries.",
        "A platypus’s bill contains electroreceptors to help detect prey.",
        "Elephants use their trunks to trumpet, drink, and pick up objects.",
        "A group of dolphins is called a 'pod.'",
        "The Komodo dragon’s venom can cause severe infections and death to its prey.",
        "The smallest bird in the world is the bee hummingbird, measuring about 2.4 inches long.",
        "A group of zebras is called a 'dazzle.'",
        "The cheetah’s claws are non-retractable, providing better traction while running.",
        "A giraffe’s tongue can be up to 18 inches long.",
        "A group of flamingos is called a 'flamboyance.'",
        "A horse’s teeth take up more space in its head than its brain.",
        "The giant panda spends most of its day eating bamboo.",
        "A crocodile’s jaw muscles are incredibly powerful, able to crush large bones.",
        "The African gray parrot is known for its ability to mimic human speech.",
        "A group of pugs is called a 'grumble.'",
        "The blue whale’s tongue can weigh as much as an elephant.",
        "The honeybee’s wings beat up to 11,400 times per minute.",
        "A zebra’s stripes are unique to each individual, much like human fingerprints.",
        "The Arctic fox has a thick, warm coat that changes color with the seasons.",
        "Sea otters have pockets in their armpits to store food and tools.",
        "The wandering albatross has the largest wingspan of any bird, up to 12 feet.",
        "A kangaroo’s tail is used for balance while hopping and is strong enough to support its weight.",
        "The giant squid has the largest eyes of any animal, measuring up to 10 inches in diameter.",
        "The golden poison dart frog is one of the most poisonous animals in the world, with enough toxin to kill several humans.",
        "Penguins propose to their mates with a pebble.",
        "The average lifespan of a housefly is only 28 days.",
        "The axolotl, also known as the Mexican salamander, never undergoes metamorphosis and retains its larval features throughout its life.",
        "Bats are the only mammals capable of true flight.",
        "Octopuses can change both the color and texture of their skin for camouflage.",
        "The great white shark can go without eating for weeks or even months at a time.",
        "The horn of a rhinoceros is made of keratin, the same substance as human hair and nails.",
        "A zebra’s stripes are unique to each individual, similar to human fingerprints.",
        "The shortest known war between two countries was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
        "The peregrine falcon is the fastest bird, reaching speeds of over 240 miles per hour during its hunting dive.",
        "Butterflies taste with their feet.",
        "Elephant tusks are actually enlarged incisor teeth that continue to grow throughout their lives.",
        "A single colony of honeybees can contain up to 60,000 individuals.",
        "A group of kangaroos is known as a 'mob.'",
        "Sloths have a very slow metabolism, which is why they move so slowly.",
        "Giraffes only need to drink once every few days, getting most of their water from their food.",
        "The wombat's poop is cube-shaped to prevent it from rolling away and marking its territory.",
        "Sea turtles can live for over 100 years.",
        "A group of goats is called a 'trip.'",
        "The largest rodent in the world is the capybara.",
        "A cheetah’s claws are non-retractable, providing better traction while running at high speeds.",
        "The blue whale's heart can weigh as much as an average car.",
        "The platypus can detect electric fields through its bill.",
        "A giraffe’s heart weighs about 25 pounds and has to pump blood all the way up to its brain.",
        "Sea horses are the only species where the male carries and gives birth to the young.",
        "The largest insect in the world by wingspan is the Atlas moth, which can have a wingspan of up to 12 inches.",
        "A chimpanzee's DNA is about 98% similar to that of humans.",
        "The Komodo dragon has a bite that is venomous and can cause serious infection.",
        "A squid’s ink is used to confuse predators and can be used to temporarily blind them.",
        "Elephants can recognize themselves in a mirror, a sign of self-awareness.",
        "Bees have been found to have a sense of smell and can distinguish between different flowers.",
        "The kiwi bird is the only bird with nostrils at the end of its beak.",
        "A group of flamingos is called a 'flamboyance.'",
        "The eyes of a camel are protected by three eyelids and two sets of eyelashes.",
        "The narwhal’s tusk is actually a tooth that can grow up to 10 feet long.",
        "Bison can run up to 40 miles per hour despite their size.",
        "A group of ravens is called an 'unkindness.'",
        "The African bullfrog can inflate its body to deter predators.",
        "A giraffe’s neck has the same number of vertebrae as a human’s, just much longer.",
        "The only mammal capable of flight is the bat.",
        "The lion’s mane jellyfish has tentacles that can extend up to 120 feet.",
        "A group of owls is called a 'parliament.'",
        "The hammerhead shark has a unique head shape that helps it locate prey.",
        "The quokka is known as the 'world's happiest animal' due to its smile-like expression.",
        "The eyes of a chameleon can move independently of each other.",
        "The slow loris is the only venomous primate.",
        "A newborn kangaroo is the size of a lima bean.",
        "The blue-footed booby is known for its vibrant blue feet that play a role in mating rituals.",
        "The glowworm is not actually a worm but the larval stage of a beetle.",
        "The Arctic fox can change the color of its fur to blend into its environment.",
        "The Great Barrier Reef is the largest living structure on Earth, visible from space.",
        "The manta ray can have a wingspan of up to 29 feet.",
        "The toucan’s beak is large but lightweight, helping it to balance while flying.",
        "A group of porcupines is called a 'prickle.'",
        "The red panda is not actually a bear but belongs to its own unique family.",
        "The jellyfish is 95% water and has no brain, heart, or bones.",
        "A meerkat’s call can be heard over a distance of 2 miles.",
        "The giraffe’s spots are like human fingerprints, unique to each individual.",
        "A baby elephant can weigh over 200 pounds at birth.",
        "The largest species of penguin is the Emperor Penguin, which can stand up to 4 feet tall.",
        "The lynx has tufted ears that help it hear prey from a distance.",
        "The Japanese spider crab has the longest legs of any crustacean, reaching up to 12 feet.",
        "A tiger’s stripes are as unique as human fingerprints.",
        "The African elephant’s trunk has over 40,000 muscles.",
        "The cheetah’s acceleration is faster than that of most sports cars.",
        "The star-nosed mole has 22 fleshy tentacles around its nose that help it detect food.",
        "The walrus has a unique set of tusks that can grow up to 3 feet long.",
        "The seahorse is the only animal in which the male gets pregnant.",
        "The giant tortoise can live to be over 150 years old.",
        "The Arctic Tern has the longest migration of any animal, traveling between the Arctic and Antarctic each year.",
        "The peregrine falcon is the fastest bird, reaching speeds of over 240 miles per hour.",
        "A single elephant can consume up to 300 pounds of food in a day.",
        "The platypus is one of the few mammals that produce venom.",
        "The Komodo dragon’s saliva contains toxic bacteria that can cause serious infections.",
        "The bison's hump is made of muscle, which helps it to push through snow.",
        "The largest rodent in the world is the capybara, which can weigh up to 150 pounds.",
        "A polar bear’s skin is black, which helps it absorb heat from the sun.",
        "The sea otter has a special pocket under its forearm to store food and tools.",
        "The hummingbird’s heart can beat up to 1,200 times per minute.",
        "The hippopotamus’s sweat is red and acts as a natural sunscreen.",
        "The giraffe’s heart has to pump blood up to its brain, which is about 10 feet above its body.",
        "The elephant’s ears help to regulate its body temperature.",
        "The axolotl can regrow entire limbs, spinal cord, and heart.",
        "The cheetah’s claws are non-retractable, which helps it maintain traction while running at high speeds.",
        "The blue whale’s tongue alone can weigh as much as an elephant.",
        "The platypus lays eggs but also produces milk for its young.",
        "The camouflaged leaf-tailed gecko can blend in perfectly with its surroundings.",
        "A group of jellyfish is called a 'smack.'",
        "The giraffe’s neck is long but has the same number of vertebrae as a human’s neck.",
        "The mantis shrimp’s punch is one of the fastest movements in the animal kingdom.",
        "The Komodo dragon has a venomous bite that can cause severe infections.",
        "The red-eyed tree frog has bright red eyes that are believed to startle predators.",
        "The axolotl never undergoes metamorphosis and retains its larval features throughout its life.",
        "The kiwi is the only bird with nostrils at the end of its beak.",
        "A group of ravens is known as an 'unkindness.'",
        "The pangolin’s scales are made of keratin, the same substance as human hair and nails.",
        "The polar bear’s fur is actually transparent, and its skin is black.",
        "The toucan’s large beak helps it stay cool by regulating body temperature.",
        "The pangolin is the only mammal wholly covered in scales.",
        "The golden eagle can have a wingspan of up to 7.5 feet.",
        "The honeybee is the only insect that produces food eaten by humans.",
        "The African elephant has the largest ears of any land animal.",
        "The Great White Shark can go without eating for several weeks at a time.",
        "The giraffe’s long neck allows it to reach high branches for feeding.",
        "The axolotl is often used in scientific research due to its regenerative abilities.",
        "The sloth’s slow movements are an adaptation to its low-energy diet of leaves.",
        "The emperor penguin is the only penguin species that breeds during the Antarctic winter.",
        "The narwhal’s tusk is actually an elongated tooth that can grow up to 10 feet long.",
        "A group of whales is called a 'pod.'",
        "The Komodo dragon can weigh up to 200 pounds and is capable of taking down large prey.",
        "The sea urchin’s spines are used for defense and locomotion.",
        "The koala’s fingerprints are almost identical to human fingerprints.",
        "A group of hedgehogs is called a 'prickle.'",
        "The cheetah’s acceleration is faster than that of most sports cars.",
        "The blue whale is the largest animal ever known to have existed.",
        "The peregrine falcon can dive at speeds exceeding 240 miles per hour.",
        "The horned lizard can shoot blood from its eyes as a defense mechanism.",
        "A group of elephants is called a 'herd.'",
        "The giant squid’s eyes are the largest of any animal.",
        "The great white shark has been around for over 400 million years.",
        "The mantis shrimp can see polarized light, which is invisible to humans.",
        "The African gray parrot can mimic human speech and has been shown to understand complex concepts.",
        "The butterfly's life cycle includes four stages: egg, larva, pupa, and adult.",
        "The starfish can regenerate lost arms and even an entire new starfish from a single arm.",
        "The giraffe’s long legs allow it to run at speeds of up to 35 miles per hour.",
        "A group of cheetahs is known as a 'coalition.'",
        "The pangolin’s scales are used in traditional medicine, although this practice is harmful to the species.",
        "The blue-footed booby’s feet are bright blue due to pigments in their diet.",
        "The Japanese macaque, also known as the snow monkey, is known for bathing in hot springs.",
        "The bearded dragon can perform push-ups to show dominance or attract a mate.",
        "The green sea turtle can live to be over 80 years old.",
        "The armadillo can roll into a ball to protect itself from predators.",
        "The komodo dragon can detect carrion from several miles away.",
        "The giant panda’s diet consists almost entirely of bamboo, though it is a member of the order Carnivora.",
        "The velvet ant, despite its name, is actually a wingless wasp and is one of the most painful stings in the insect world.",
        "The hummingbird’s metabolism is so high that it can beat its wings up to 80 times per second.",
        "The cuttlefish can change its skin color and texture to blend into its surroundings.",
        "The sea otter’s fur is the densest of any animal, with up to 600,000 hairs per square inch.",
        "The octopus has three hearts and blue blood.",
        "The whale shark is the largest fish in the world but feeds only on plankton.",
        "The bongo antelope has striking reddish-brown fur with white stripes.",
        "The albino alligator is a rare genetic variant of the American alligator.",
        "The great white shark has a keen sense of smell and can detect a drop of blood in 25 gallons of water.",
        "The giant squid has a beak that can tear through flesh.",
        "The fennec fox has large ears that help dissipate heat.",
        "The scarab beetle was revered in ancient Egypt and considered a symbol of protection.",
        "The giant tortoise can live for over 150 years and has a slow metabolism.",
        "The wolf spider’s bite can be painful but is not dangerous to humans.",
        "The axolotl is sometimes referred to as the 'Mexican walking fish,' though it is not a fish but an amphibian.",
        "The gray wolf is the largest member of the dog family and can weigh up to 175 pounds.",
        "The red fox is one of the most widely distributed wild mammals.",
        "The hummingbird’s metabolism is so fast that it can consume twice its body weight in a day.",
        "The Brazilian wandering spider is one of the most venomous spiders in the world.",
        "The cheetah’s distinctive black tear marks help reduce glare from the sun.",
        "The golden eagle can see up to 3.2 miles away.",
        "The lemur’s tail is longer than its body and helps with balance.",
        "The sea cucumber can expel its internal organs as a defense mechanism.",
        "The cuttlefish’s color-changing abilities are due to specialized cells called chromatophores.",
        "The lionfish is an invasive species in the Atlantic Ocean and has venomous spines.",
        "The hammerhead shark’s head shape provides a 360-degree view of its surroundings.",
        "The pangolin is the only mammal wholly covered in scales.",
        "The Komodo dragon’s venom contains toxins that can prevent blood clotting.",
        "The albino kangaroo is a rare genetic variant of the common kangaroo.",
        "The hedgehog’s spines are made of keratin, the same substance as human hair and nails.",
        "The giant squid’s arms have tiny, sharp teeth that help capture prey.",
        "The capybara is a semi-aquatic rodent native to South America.",
        "The narwhal’s tusk is actually a tooth that grows through the top of its head.",
        "The African elephant is the largest land animal and can weigh up to 14,000 pounds.",
        "The dodo, an extinct flightless bird, was native to Mauritius.",
        "The kiwi is a flightless bird with a keen sense of smell.",
        "The leopard seal has one of the strongest bites among marine mammals.",
        "The orangutan is one of the most intelligent non-human animals and can use tools.",
        "The great white shark’s jaw contains up to 300 teeth arranged in multiple rows.",
        "The octopus can change its color and texture to match its surroundings.",
        "The Arctic fox’s fur changes color with the seasons, from white in winter to brown in summer.",
        "The Komodo dragon can reach speeds of up to 12 miles per hour.",
        "The snow leopard is known for its beautiful, spotted fur and its ability to leap 50 feet in a single bound.",
        "The giraffe’s long neck allows it to feed on leaves high up in trees.",
        "The golden poison dart frog is one of the most poisonous animals on Earth.",
        "The giant panda’s thumb is an adaptation of a wrist bone used to grasp bamboo.",
        "The narwhal’s tusk can grow up to 10 feet long and is often mistaken for a horn.",
        "The wandering albatross has the largest wingspan of any bird, reaching up to 12 feet.",
        "The star-nosed mole uses its unique nose to detect food in the dark.",
        "The African elephant’s trunk is an incredibly versatile tool used for feeding, drinking, and social interactions.",
        "The red panda’s diet consists mainly of bamboo, but it also eats fruits and insects.",
        "The bearded dragon is known for its unique beard-like throat flap that it can puff up when threatened.",
        "The emperor penguin is the only penguin species that breeds during the Antarctic winter.",
        "The hammerhead shark’s head shape allows it to detect electrical signals from prey.",
        "The jellyfish is made up of 95% water and has no brain, heart, or bones.",
        "The armadillo’s hard shell provides protection from predators.",
        "The red-eyed tree frog uses its bright coloration to startle predators.",
        "The starfish can regenerate lost arms and even entire new starfish from a single arm.",
        "The blue-footed booby performs a courtship dance to attract mates.",
        "The giant squid’s eyes are the largest in the animal kingdom, reaching up to 10 inches in diameter.",
        "The fennec fox has large ears that help it detect prey and regulate body temperature.",
        "The African gray parrot can mimic human speech and understand complex concepts.",
        "The lion’s mane jellyfish has tentacles that can extend up to 120 feet.",
        "The kiwi is the only bird with nostrils at the end of its beak.",
        "The axolotl is often used in scientific research due to its regenerative abilities.",
        "The hippopotamus’s sweat is red and acts as a natural sunscreen.",
        "The red fox is one of the most widely distributed wild mammals.",
        "The green sea turtle can live for over 80 years.",
        "The giant tortoise can live to be over 150 years old.",
        "The great white shark has been around for over 400 million years.",
        "The mantis shrimp’s punch is one of the fastest movements in the animal kingdom.",
        "The giant panda’s diet consists almost entirely of bamboo, though it is a member of the order Carnivora.",
        "The peregrine falcon can dive at speeds exceeding 240 miles per hour.",
        "The golden eagle can see up to 3.2 miles away.",
        "The bearded dragon’s beard is used to display dominance and attract mates.",
        "The great white shark has a keen sense of smell and can detect a drop of blood in 25 gallons of water.",
        "The cuttlefish’s color-changing abilities are due to specialized cells called chromatophores.",
        "The lemur’s tail is longer than its body and helps with balance.",
        "The polar bear’s fur is actually transparent, and its skin is black.",
        "The snow leopard is known for its beautiful, spotted fur and its ability to leap 50 feet in a single bound.",
        "The jellyfish is 95% water and has no brain, heart, or bones.",
        "The armadillo’s hard shell provides protection from predators.",
        "The axolotl can regenerate entire limbs, spinal cord, and heart.",
        "The zebra’s stripes are unique to each individual, much like human fingerprints.",
        "The giant squid’s arms have tiny, sharp teeth that help capture prey.",
        "The walrus has a unique set of tusks that can grow up to 3 feet long.",
        "The green sea turtle can live to be over 80 years old.",
        "The koala’s fingerprints are almost identical to human fingerprints.",
        "The capybara is a semi-aquatic rodent native to South America.",
        "The giant tortoise can live to be over 150 years old.",
        "The Japanese macaque is known for bathing in hot springs.",
        "The bearded dragon can perform push-ups to show dominance or attract a mate.",
        "The golden poison dart frog is one of the most poisonous animals in the world.",
        "The seahorse is the only animal in which the male gets pregnant.",
        "The Arctic Tern has the longest migration of any animal, traveling between the Arctic and Antarctic each year.",
        "The largest rodent in the world is the capybara.",
        "The kangaroo’s tail is used for balance while hopping.",
        "The fennec fox has large ears that help dissipate heat.",
        "The mantis shrimp has the most complex visual system in the animal kingdom.",
        "The star-nosed mole has 22 fleshy tentacles around its nose that help it detect food.",
        "The golden eagle can see up to 3.2 miles away.",
        "The narwhal’s tusk is actually an elongated tooth that can grow up to 10 feet long.",
        "The emperor penguin is the only penguin species that breeds during the Antarctic winter.",
        "The African gray parrot can mimic human speech and understand complex concepts.",
        "The leopard seal has one of the strongest bites among marine mammals.",
        "The armadillo can roll into a ball to protect itself from predators.",
        "The great white shark can go without eating for several weeks at a time.",
        "The giraffe’s long neck allows it to feed on leaves high up in trees.",
        "The blue-footed booby performs a courtship dance to attract mates.",
        "The jellyfish is made up of 95% water and has no brain, heart, or bones.",
        "The giant squid’s eyes are the largest in the animal kingdom, reaching up to 10 inches in diameter.",
        "The fennec fox has large ears that help it detect prey and regulate body temperature.",
        "The giant panda’s thumb is an adaptation of a wrist bone used to grasp bamboo.",
        "The sea urchin’s spines are used for defense and locomotion.",
        "The golden poison dart frog is one of the most poisonous animals on Earth.",
        "The red panda’s diet consists mainly of bamboo, but it also eats fruits and insects.",
        "The bearded dragon’s beard is used to display dominance and attract mates.",
        "The hammerhead shark’s head shape allows it to detect electrical signals from prey.",
        "The Komodo dragon can weigh up to 200 pounds and is capable of taking down large prey.",
        "The sea otter’s fur is the densest of any animal, with up to 600,000 hairs per square inch.",
        "The armadillo’s hard shell provides protection from predators.",
        "The red-eyed tree frog uses its bright coloration to startle predators.",
        "The starfish can regenerate lost arms and even an entire new starfish from a single arm.",
        "The blue-footed booby performs a courtship dance to attract mates.",
        "The giant squid’s arms have tiny, sharp teeth that help capture prey.",
        "The capybara is a semi-aquatic rodent native to South America.",
        "The narwhal’s tusk can grow up to 10 feet long and is often mistaken for a horn.",
        "The African elephant has the largest ears of any land animal.",
        "The dodo, an extinct flightless bird, was native to Mauritius.",
        "The kiwi is a flightless bird with a keen sense of smell.",
        "The leopard seal has one of the strongest bites among marine mammals.",
        "The orangutan is one of the most intelligent non-human animals and can use tools.",
        "The great white shark’s jaw contains up to 300 teeth arranged in multiple rows.",
        "The octopus can change its color and texture to match its surroundings.",
        "The Arctic fox’s fur changes color with the seasons, from white in winter to brown in summer.",
        "The Komodo dragon can reach speeds of up to 12 miles per hour.",
        "The snow leopard is known for its beautiful, spotted fur and its ability to leap 50 feet in a single bound.",
        "The giraffe’s long neck allows it to feed on leaves high up in trees.",
        "The golden poison dart frog is one of the most poisonous animals on Earth.",
        "The giant panda’s thumb is an adaptation of a wrist bone used to grasp bamboo.",
        "The narwhal’s tusk can grow up to 10 feet long and is often mistaken for a horn.",
        "The wandering albatross has the largest wingspan of any bird, reaching up to 12 feet.",
        "The star-nosed mole uses its unique nose to detect food in the dark.",
        "The African elephant’s trunk is an incredibly versatile tool used for feeding, drinking, and social interactions.",
        "The red panda’s diet consists mainly of bamboo, but it also eats fruits and insects.",
        "The bearded dragon is known for its unique beard-like throat flap that it can puff up when threatened.",
        "The emperor penguin is the only penguin species that breeds during the Antarctic winter.",
        "The hammerhead shark’s head shape allows it to detect electrical signals from prey.",
        "The jellyfish is made up of 95% water and has no brain, heart, or bones.",
        "The armadillo’s hard shell provides protection from predators.",
        "The red-eyed tree frog uses its bright coloration to startle predators.",
        "The starfish can regenerate lost arms and even an entire new starfish from a single arm.",
        "The blue-footed booby performs a courtship dance to attract mates.",
        "The giant squid’s eyes are the largest in the animal kingdom, reaching up to 10 inches in diameter.",
        "The fennec fox has large ears that help it detect prey and regulate body temperature.",
        "The giant panda’s thumb is an adaptation of a wrist bone used to grasp bamboo.",
        "The sea urchin’s spines are used for defense and locomotion.",
        "The golden poison dart frog is one of the most poisonous animals on Earth.",
        "The red panda’s diet consists mainly of bamboo, but it also eats fruits and insects.",
        "The bearded dragon’s beard is used to display dominance and attract mates.",
        "The hammerhead shark’s head shape allows it to detect electrical signals from prey.",
        "The Komodo dragon can weigh up to 200 pounds and is capable of taking down large prey.",
        "The sea otter’s fur is the densest of any animal, with up to 600,000 hairs per square inch.",
        "The armadillo’s hard shell provides protection from predators.",
        "The red-eyed tree frog uses its bright coloration to startle predators.",
        "The starfish can regenerate lost arms and even an entire new starfish from a single arm.",
        "The blue-footed booby performs a courtship dance to attract mates.",
        "The giant squid’s arms have tiny, sharp teeth that help capture prey.",
        "The capybara is a semi-aquatic rodent native to South America.",
        "The narwhal’s tusk can grow up to 10 feet long and is often mistaken for a horn.",
        "The African elephant has the largest ears of any land animal.",
        "The dodo, an extinct flightless bird, was native to Mauritius.",
        "The kiwi is a flightless bird with a keen sense of smell.",
        "The leopard seal has one of the strongest bites among marine mammals.",
        "The orangutan is one of the most intelligent non-human animals and can use tools.",
        "The great white shark’s jaw contains up to 300 teeth arranged in multiple rows.",
        "The octopus can change its color and texture to match its surroundings.",
        "The Arctic fox’s fur changes color with the seasons, from white in winter to brown in summer.",
        "The Komodo dragon can reach speeds of up to 12 miles per hour.",
        "The snow leopard is known for its beautiful, spotted fur and its ability to leap 50 feet in a single bound.",
        "The giraffe’s long neck allows it to feed on leaves high up in trees.",
        "The golden poison dart frog is one of the most poisonous animals on Earth.",
        "The giant panda’s thumb is an adaptation of a wrist bone used to grasp bamboo.",
        "The narwhal’s tusk can grow up to 10 feet long and is often mistaken for a horn.",
        "The wandering albatross has the largest wingspan of any bird, reaching up to 12 feet.",
        "The star-nosed mole uses its unique nose to detect food in the dark.",
        "The African elephant’s trunk is an incredibly versatile tool used for feeding, drinking, and social interactions.",
        "The red panda’s diet consists mainly of bamboo, but it also eats fruits and insects.",
        "The bearded dragon is known for its unique beard-like throat flap that it can puff up when threatened.",
        "The emperor penguin is the only penguin species that breeds during the Antarctic winter.",
        "The hammerhead shark’s head shape allows it to detect electrical signals from prey.",
        "The jellyfish is made up of 95% water and has no brain, heart, or bones.",
        "The armadillo’s hard shell provides protection from predators.",
        "The red-eyed tree frog uses its bright coloration to startle predators.",
        "The starfish can regenerate lost arms and even an entire new starfish from a single arm.",
        "The blue-footed booby performs a courtship dance to attract mates.",
        "The giant squid’s eyes are the largest in the animal kingdom, reaching up to 10 inches in diameter.",
        "The fennec fox has large ears that help it detect prey and regulate body temperature.",
        "The giant panda’s thumb is an adaptation of a wrist bone used to grasp bamboo.",
        "The sea urchin’s spines are used for defense and locomotion.",
        "The golden poison dart frog is one of the most poisonous animals on Earth.",
        "The red panda’s diet consists mainly of bamboo, but it also eats fruits and insects.",
        "The bearded dragon’s beard is used to display dominance and attract mates.",
        "The hammerhead shark’s head shape allows it to detect electrical signals from prey.",
        "The Komodo dragon can weigh up to 200 pounds and is capable of taking down large prey.",
        "The sea otter’s fur is the densest of any animal, with up to 600,000 hairs per square inch.",
        "The armadillo’s hard shell provides protection from predators.",
        "The red-eyed tree frog uses its bright coloration to startle predators.",
        "The starfish can regenerate lost arms and even an entire new starfish from a single arm.",
        "The blue-footed booby performs a courtship dance to attract mates.",
        "The giant squid’s arms have tiny, sharp teeth that help capture prey.",
        "The capybara is a semi-aquatic rodent native to South America.",
        "The narwhal’s tusk can grow up to 10 feet long and is often mistaken for a horn.",
        "The African elephant has the largest ears of any land animal.",
        "The dodo, an extinct flightless bird, was native to Mauritius.",
        "The kiwi is a flightless bird with a keen sense of smell.",
        "The leopard seal has one of the strongest bites among marine mammals.",
        "The orangutan is one of the most intelligent non-human animals and can use tools.",
        "The great white shark’s jaw contains up to 300 teeth arranged in multiple rows.",
        "The octopus can change its color and texture to match its surroundings.",
        "The Arctic fox’s fur changes color with the seasons, from white in winter to brown in summer.",
        "The Komodo dragon can reach speeds of up to 12 miles per hour.",
        "The snow leopard is known for its beautiful, spotted fur and its ability to leap 50 feet in a single bound.",
        "The giraffe’s long neck allows it to feed on leaves high up in trees.",
        "The golden poison dart frog is one of the most poisonous animals on Earth.",
        "The giant panda’s thumb is an adaptation of a wrist bone used to grasp bamboo.",
        "The narwhal’s tusk can grow up to 10 feet long and is often mistaken for a horn.",
        "The wandering albatross has the largest wingspan of any bird, reaching up to 12 feet.",
        "The star-nosed mole uses its unique nose to detect food in the dark.",
        "The African elephant’s trunk is an incredibly versatile tool used for feeding, drinking, and social interactions.",
        "The red panda’s diet consists mainly of bamboo, but it also eats fruits and insects.",
        "The bearded dragon is known for its unique beard-like throat flap that it can puff up when threatened.",
        "The emperor penguin is the only penguin species that breeds during the Antarctic winter.",
        "The hammerhead shark’s head shape allows it to detect electrical signals from prey.",
        "The jellyfish is made up of 95% water and has no brain, heart, or bones.",
        "The armadillo’s hard shell provides protection from predators.",
        "The red-eyed tree frog uses its bright coloration to startle predators.",
        "The starfish can regenerate lost arms and even an entire new starfish from a single arm.",
        "The blue-footed booby performs a courtship dance to attract mates.",
        "The giant squid’s eyes are the largest in the animal kingdom, reaching up to 10 inches in diameter.",
        "The fennec fox has large ears that help it detect prey and regulate body temperature.",
        "The giant panda’s thumb is an adaptation of a wrist bone used to grasp bamboo.",
        "The sea urchin’s spines are used for defense and locomotion.",
        "The golden poison dart frog is one of the most poisonous animals on Earth.",
        "The red panda’s diet consists mainly of bamboo, but it also eats fruits and insects.",
        "The bearded dragon’s beard is used to display dominance and attract mates.",
        "The hammerhead shark’s head shape allows it to detect electrical signals from prey.",
        "The Komodo dragon can weigh up to 200 pounds and is capable of taking down large prey.",
        "The sea otter’s fur is the densest of any animal, with up to 600,000 hairs per square inch.",
        "The armadillo’s hard shell provides protection from predators.",
        "The red-eyed tree frog uses its bright coloration to startle predators.",
        "The starfish can regenerate lost arms and even an entire new starfish from a single arm.",
        "The blue-footed booby performs a courtship dance to attract mates.",
        "The giant squid’s arms have tiny, sharp teeth that help capture prey.",
        "The capybara is a semi-aquatic rodent native to South America.",
        "The narwhal’s tusk can grow up to 10 feet long and is often mistaken for a horn.",
        "The African elephant has the largest ears of any land animal.",
        "The dodo, an extinct flightless bird, was native to Mauritius.",
        "The kiwi is a flightless bird with a keen sense of smell.",
        "The leopard seal has one of the strongest bites among marine mammals.",
        "The orangutan is one of the most intelligent non-human animals and can use tools.",
        "The great white shark’s jaw contains up to 300 teeth arranged in multiple rows.",
        "The octopus can change its color and texture to match its surroundings.",
        "The Arctic fox’s fur changes color with the seasons, from white in winter to brown in summer.",
        "The Komodo dragon can reach speeds of up to 12 miles per hour.",
        "The snow leopard is known for its beautiful, spotted fur and its ability to leap 50 feet in a single bound.",
        "The giraffe’s long neck allows it to feed on leaves high up in trees.",
        "The golden poison dart frog is one of the most poisonous animals on Earth.",
        "The giant panda’s thumb is an adaptation of a wrist bone used to grasp bamboo.",
        "The narwhal’s tusk can grow up to 10 feet long and is often mistaken for a horn.",
        "The wandering albatross has the largest wingspan of any bird, reaching up to 12 feet.",
        "The star-nosed mole uses its unique nose to detect food in the dark.",
        "The African elephant’s trunk is an incredibly versatile tool used for feeding, drinking, and social interactions.",
        "The red panda’s diet consists mainly of bamboo, but it also eats fruits and insects.",
        "The bearded dragon is known for its unique beard-like throat flap that it can puff up when threatened.",
        "The emperor penguin is the only penguin species that breeds during the Antarctic winter.",
        "The hammerhead shark’s head shape allows it to detect electrical signals from prey.",
        "The jellyfish is made up of 95% water and has no brain, heart, or bones.",
        "The armadillo’s hard shell provides protection from predators.",
        "The red-eyed tree frog uses its bright coloration to startle predators.",
        "The starfish can regenerate lost arms and even an entire new starfish from a single arm.",
        "The blue-footed booby performs a courtship dance to attract mates.",
        "The giant squid’s eyes are the largest in the animal kingdom, reaching up to 10 inches in diameter.",
        "The fennec fox has large ears that help it detect prey and regulate body temperature.",
        "The giant panda’s thumb is an adaptation of a wrist bone used to grasp bamboo.",
        "The sea urchin’s spines are used for defense and locomotion.",
        "The golden poison dart frog is one of the most poisonous animals on Earth.",
        "The red panda’s diet consists mainly of bamboo, but it also eats fruits and insects.",
        "The bearded dragon’s beard is used to display dominance and attract mates.",
        "The hammerhead shark’s head shape allows it to detect electrical signals from prey.",
        "The Komodo dragon can weigh up to 200 pounds and is capable of taking down large prey.",
        "The sea otter’s fur is the densest of any animal, with up to 600,000 hairs per square inch.",
        "The armadillo’s hard shell provides protection from predators.",
        "The red-eyed tree frog uses its bright coloration to startle predators.",
        "The starfish can regenerate lost arms and even an entire new starfish from a single arm.",
        "The blue-footed booby performs a courtship dance to attract mates.",
        "The giant squid’s arms have tiny, sharp teeth that help capture prey.",
        "The capybara is a semi-aquatic rodent native to South America.",
        "The narwhal’s tusk can grow up to 10 feet long and is often mistaken for a horn.",
        "The African elephant has the largest ears of any land animal.",
        "The dodo, an extinct flightless bird, was native to Mauritius.",
        "The kiwi is a flightless bird with a keen sense of smell.",
        "The leopard seal has one of the strongest bites among marine mammals.",
        "The orangutan is one of the most intelligent non-human animals and can use tools.",
        "The great white shark’s jaw contains up to 300 teeth arranged in multiple rows.",
        "The octopus can change its color and texture to match its surroundings.",
        "The Arctic fox’s fur changes color with the seasons, from white in winter to brown in summer.",
        "The Komodo dragon can reach speeds of up to 12 miles per hour.",
        "The snow leopard is known for its beautiful, spotted fur and its ability to leap 50 feet in a single bound.",
        "The giraffe’s long neck allows it to feed on leaves high up in trees.",
        "The golden poison dart frog is one of the most poisonous animals on Earth.",
        "The giant panda’s thumb is an adaptation of a wrist bone used to grasp bamboo.",
        "The narwhal’s tusk can grow up to 10 feet long and is often mistaken for a horn.",
        "The wandering albatross has the largest wingspan of any bird, reaching up to 12 feet.",
        "The star-nosed mole uses its unique nose to detect food in the dark.",
        "The African elephant’s trunk is an incredibly versatile tool used for feeding, drinking, and social interactions.",
        "The red panda’s diet consists mainly of bamboo, but it also eats fruits and insects.",
        "The bearded dragon is known for its unique beard-like throat flap that it can puff up when threatened.",
        "The emperor penguin is the only penguin species that breeds during the Antarctic winter.",
        "The hammerhead shark’s head shape allows it to detect electrical signals from prey.",
        "The jellyfish is made up of 95% water and has no brain, heart, or bones.",
        "The armadillo’s hard shell provides protection from predators.",
        "The red-eyed tree frog uses its bright coloration to startle predators.",
        "The starfish can regenerate lost arms and even an entire new starfish from a single arm.",
        "The blue-footed booby performs a courtship dance to attract mates.",
        "The giant squid’s eyes are the largest in the animal kingdom, reaching up to 10 inches in diameter.",
        "The fennec fox has large ears that help it detect prey and regulate body temperature.",
        "The giant panda’s thumb is an adaptation of a wrist bone used to grasp bamboo.",
        "The sea urchin’s spines are used for defense and locomotion.",
        "The golden poison dart frog is one of the most poisonous animals on Earth.",
        "The red panda’s diet consists mainly of bamboo, but it also eats fruits and insects.",
        "The bearded dragon’s beard is used to display dominance and attract mates.",
        "The hammerhead shark’s head shape allows it to detect electrical signals from prey.",
        "The Komodo dragon can weigh up to 200 pounds and is capable of taking down large prey.",
        "The sea otter’s fur is the densest of any animal, with up to 600,000 hairs per square inch.",
        "The armadillo’s hard shell provides protection from predators.",
        "The red-eyed tree frog uses its bright coloration to startle predators.",
        "The starfish can regenerate lost arms and even an entire new starfish from a single arm.",
        "The blue-footed booby performs a courtship dance to attract mates.",
        "The giant squid’s arms have tiny, sharp teeth that help capture prey.",
        "The capybara is a semi-aquatic rodent native to South America.",
        "The narwhal’s tusk can grow up to 10 feet long and is often mistaken for a horn.",
        "The African elephant has the largest ears of any land animal.",
        "The dodo, an extinct flightless bird, was native to Mauritius.",
        "The kiwi is a flightless bird with a keen sense of smell.",
        "The leopard seal has one of the strongest bites among marine mammals.",
        "The orangutan is one of the most intelligent non-human animals and can use tools.",
        "The great white shark’s jaw contains up to 300 teeth arranged in multiple rows.",
        "The octopus can change its color and texture to match its surroundings.",
        "The Arctic fox’s fur changes color with the seasons, from white in winter to brown in summer.",
        "The Komodo dragon can reach speeds of up to 12 miles per hour.",
        "The snow leopard is known for its beautiful, spotted fur and its ability to leap 50 feet in a single bound.",
        "The giraffe’s long neck allows it to feed on leaves high up in trees.",
        "The golden poison dart frog is one of the most poisonous animals on Earth.",
        "The giant panda’s thumb is an adaptation of a wrist bone used to grasp bamboo.",
        "The narwhal’s tusk can grow up to 10 feet long and is often mistaken for a horn.",
        "The wandering albatross has the largest wingspan of any bird, reaching up to 12 feet.",
        "The star-nosed mole uses its unique nose to detect food in the dark.",
        "The African elephant’s trunk is an incredibly versatile tool used for feeding, drinking."
    ]
    function onClickFactHandler() {
        setFact(facts[Math.floor(Math.random() * (539))])
    }
    const [fact, setFact] = useState("Click the button for a random fact")
    return (
        <div className="randomfact">
            <p>{fact}</p>
            <button onClick={onClickFactHandler}>Generate</button>
        </div>
    );
}

export default RandomFact